//! Replay the Python simulator's blind, boss, deck, tag, pack and voucher data.
//!
//! The fixture is generated by `tools/gen_blinds_fixture.py` against the Python
//! original. Floats are written with `%.17g`, so the comparison is on bits
//! rather than on printed digits -- which is the only test that separates
//! replication from coincidence. The deck, tag, pack and voucher records are in
//! the Python pool order, so a reordered table fails here too: the order decides
//! what a seeded draw lands on.

use std::collections::HashMap;

use rumbot_sim::blinds::{
    all_bosses, ante_base_chips, boss_by_name, make_blind, reward_for, BlindKind, BOSSES,
    FINISHER_BOSSES, FINISHER_REWARD,
};
use rumbot_sim::boss_data::eligible_bosses;
use rumbot_sim::cards::Suit;
use rumbot_sim::deck_data::{deck_config, DeckConfig, DECK_DATA};
use rumbot_sim::pack_data::PACK_DATA;
use rumbot_sim::tag_data::{tag_row, tag_row_by_key, TAG_DATA};
use rumbot_sim::voucher_data::{voucher_row, VOUCHER_DATA};

const FIXTURE: &str = include_str!("fixtures/blinds.txt");

fn bits_eq(got: f64, want: f64, what: &str) {
    assert_eq!(
        got.to_bits(),
        want.to_bits(),
        "{}: got {:?} ({:016x}) want {:?} ({:016x})",
        what,
        got,
        got.to_bits(),
        want,
        want.to_bits()
    );
}

fn flag(s: &str) -> bool {
    s == "1"
}

/// `-` stands in for the empty string, so a tab-split never loses a column.
fn dash(s: &str) -> &str {
    if s == "-" {
        ""
    } else {
        s
    }
}

fn split_list(s: &str) -> Vec<&str> {
    if s == "-" {
        Vec::new()
    } else {
        s.split(',').collect()
    }
}

fn parse_kind(s: &str) -> BlindKind {
    match s {
        "small" => BlindKind::Small,
        "big" => BlindKind::Big,
        "boss" => BlindKind::Boss,
        other => panic!("unknown blind kind {:?}", other),
    }
}

fn parse_suit(s: &str) -> Option<Suit> {
    match s {
        "-" => None,
        "S" => Some(Suit::Spades),
        "H" => Some(Suit::Hearts),
        "D" => Some(Suit::Diamonds),
        "C" => Some(Suit::Clubs),
        other => panic!("unknown suit {:?}", other),
    }
}

fn parse_used(s: &str) -> HashMap<String, i32> {
    let mut used = HashMap::new();
    if s == "-" {
        return used;
    }
    for pair in s.split(';') {
        let (key, count) = pair.split_once(':').expect("used key:count");
        used.insert(key.to_string(), count.parse().expect("used count"));
    }
    used
}

#[test]
fn the_data_matches_the_python_simulator() {
    let mut checked = 0usize;
    let mut deck_i = 0usize;
    let mut tag_i = 0usize;
    let mut pack_i = 0usize;
    let mut voucher_i = 0usize;
    for (lineno, line) in FIXTURE.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        match f[0] {
            "base" => {
                let ante: i32 = f[1].parse().unwrap();
                let scaling: i32 = f[2].parse().unwrap();
                let want: i64 = f[3].parse().unwrap();
                assert_eq!(ante_base_chips(ante, scaling), want, "{}", line);
            }
            "order" => {
                let want: Vec<&str> = f[2].split(',').collect();
                let got: Vec<&str> = if f[1] == "ordinary" {
                    BOSSES.iter().map(|b| b.name).collect()
                } else {
                    FINISHER_BOSSES.iter().map(|b| b.name).collect()
                };
                assert_eq!(got, want, "{}", line);
            }
            "boss" => {
                let boss = boss_by_name(f[1]).unwrap_or_else(|| panic!("no boss {:?}", f[1]));
                bits_eq(boss.chip_mult, f[2].parse().unwrap(), line);
                assert_eq!(boss.debuff_suit, parse_suit(f[3]), "{}", line);
                assert_eq!(boss.debuff_face, flag(f[4]), "{}", line);
                assert_eq!(
                    boss.hand_size_delta,
                    f[5].parse::<i32>().unwrap(),
                    "{}",
                    line
                );
                assert_eq!(boss.hands_delta, f[6].parse::<i32>().unwrap(), "{}", line);
                assert_eq!(
                    boss.discards_delta,
                    f[7].parse::<i32>().unwrap(),
                    "{}",
                    line
                );
                assert_eq!(
                    boss.min_cards_played,
                    f[8].parse::<i32>().unwrap(),
                    "{}",
                    line
                );
                assert_eq!(
                    boss.money_per_card_played,
                    f[9].parse::<i32>().unwrap(),
                    "{}",
                    line
                );
                assert_eq!(boss.zero_money_on_most_played, flag(f[10]), "{}", line);
                assert_eq!(
                    boss.discard_random_on_play,
                    f[11].parse::<i32>().unwrap(),
                    "{}",
                    line
                );
                assert_eq!(boss.level_down_played_hand, flag(f[12]), "{}", line);
                assert_eq!(boss.no_repeat_hand, flag(f[13]), "{}", line);
                assert_eq!(boss.lock_first_hand_type, flag(f[14]), "{}", line);
                assert_eq!(boss.debuff_previously_played, flag(f[15]), "{}", line);
                assert_eq!(boss.halve_base, flag(f[16]), "{}", line);
                assert_eq!(boss.always_draw_three, flag(f[17]), "{}", line);
                assert_eq!(boss.shuffles_jokers, flag(f[18]), "{}", line);
                assert_eq!(boss.debuff_until_sale, flag(f[19]), "{}", line);
                assert_eq!(boss.debuff_a_joker, flag(f[20]), "{}", line);
                assert_eq!(boss.forces_a_card, flag(f[21]), "{}", line);
                assert_eq!(boss.is_finisher, flag(f[22]), "{}", line);
            }
            "eligible" => {
                let ante: i32 = f[1].parse().unwrap();
                let win_ante: i32 = f[2].parse().unwrap();
                let used = parse_used(f[3]);
                let want = split_list(f[4]);
                let got = eligible_bosses(ante, &used, win_ante);
                assert_eq!(got, want, "{}", line);
            }
            "blind" => {
                let kind = parse_kind(f[1]);
                let ante: i32 = f[2].parse().unwrap();
                let ante_scaling: f64 = f[3].parse().unwrap();
                let scaling: i32 = f[4].parse().unwrap();
                let no_reward = flag(f[5]);
                let boss = if f[6] == "-" {
                    None
                } else {
                    Some(boss_by_name(f[6]).unwrap_or_else(|| panic!("no boss {:?}", f[6])))
                };
                let blind = make_blind(kind, ante, boss, ante_scaling, scaling, no_reward);
                assert_eq!(blind.target, f[7].parse::<i64>().unwrap(), "{}", line);
                assert_eq!(blind.reward, f[8].parse::<i32>().unwrap(), "{}", line);
                assert_eq!(blind.name(), f[9], "{}", line);
                assert_eq!(blind.kind, kind, "{}", line);
                assert_eq!(blind.ante, ante, "{}", line);
            }
            "deck" => {
                assert_eq!(DECK_DATA[deck_i].0, f[1], "{}", line);
                let config = deck_config(f[1]);
                assert_eq!(config.key, f[2], "{}", line);
                assert_eq!(config.remove_faces, flag(f[3]), "{}", line);
                assert_eq!(config.double_tag_after_boss, flag(f[4]), "{}", line);
                assert_eq!(config.hands, f[5].parse::<i32>().unwrap(), "{}", line);
                assert_eq!(config.joker_slot, f[6].parse::<i32>().unwrap(), "{}", line);
                assert_eq!(config.discards, f[7].parse::<i32>().unwrap(), "{}", line);
                assert_eq!(config.dollars, f[8].parse::<i32>().unwrap(), "{}", line);
                assert_eq!(config.hand_size, f[9].parse::<i32>().unwrap(), "{}", line);
                bits_eq(config.ante_scaling, f[10].parse().unwrap(), line);
                assert_eq!(
                    config.consumable_slot,
                    f[11].parse::<i32>().unwrap(),
                    "{}",
                    line
                );
                assert_eq!(config.randomize_rank_suit, flag(f[12]), "{}", line);
                assert_eq!(
                    config.extra_hand_bonus,
                    f[13].parse::<i32>().unwrap(),
                    "{}",
                    line
                );
                assert_eq!(
                    config.extra_discard_bonus,
                    f[14].parse::<i32>().unwrap(),
                    "{}",
                    line
                );
                assert_eq!(config.no_interest, flag(f[15]), "{}", line);
                assert_eq!(
                    config.spectral_rate,
                    f[16].parse::<i32>().unwrap(),
                    "{}",
                    line
                );
                assert_eq!(config.consumables, split_list(f[17]).as_slice(), "{}", line);
                assert_eq!(config.voucher, dash(f[18]), "{}", line);
                assert_eq!(config.vouchers, split_list(f[19]).as_slice(), "{}", line);
                deck_i += 1;
            }
            "tag" => {
                let row = &TAG_DATA[tag_i];
                assert_eq!(row.key, f[1], "{}", line);
                assert_eq!(row.name, f[2], "{}", line);
                assert_eq!(row.min_ante, f[3].parse::<i32>().unwrap(), "{}", line);
                assert_eq!(row.requires, dash(f[4]), "{}", line);
                assert_eq!(tag_row(f[2]).map(|r| r.key), Some(f[1]), "{}", line);
                assert_eq!(tag_row_by_key(f[1]).map(|r| r.name), Some(f[2]), "{}", line);
                tag_i += 1;
            }
            "pack" => {
                let row = &PACK_DATA[pack_i];
                assert_eq!(row.key, f[1], "{}", line);
                assert_eq!(row.kind, f[2], "{}", line);
                bits_eq(row.weight, f[3].parse().unwrap(), line);
                assert_eq!(row.choose, f[4].parse::<i32>().unwrap(), "{}", line);
                assert_eq!(row.cards, f[5].parse::<i32>().unwrap(), "{}", line);
                assert_eq!(row.cost, f[6].parse::<i32>().unwrap(), "{}", line);
                pack_i += 1;
            }
            "voucher" => {
                let row = &VOUCHER_DATA[voucher_i];
                assert_eq!(row.key, f[1], "{}", line);
                assert_eq!(row.name, f[2], "{}", line);
                assert_eq!(row.cost, f[3].parse::<i32>().unwrap(), "{}", line);
                assert_eq!(row.requires, dash(f[4]), "{}", line);
                bits_eq(row.extra, f[5].parse().unwrap(), line);
                assert_eq!(voucher_row(f[2]).map(|r| r.key), Some(f[1]), "{}", line);
                voucher_i += 1;
            }
            other => panic!("unknown fixture record {:?} at line {}", other, lineno + 1),
        }
        checked += 1;
    }
    assert_eq!(deck_i, DECK_DATA.len(), "deck rows");
    assert_eq!(tag_i, TAG_DATA.len(), "tag rows");
    assert_eq!(pack_i, PACK_DATA.len(), "pack rows");
    assert_eq!(voucher_i, VOUCHER_DATA.len(), "voucher rows");
    assert!(checked > 100, "fixture only exercised {} records", checked);
}

#[test]
fn an_unknown_deck_gets_the_empty_config() {
    // Python: DECK_DATA.get(deck, ("", {}))[1], whose .get() defaults are the
    // same ones the game reads -- ante_scaling 1, extra_hand_bonus 1.
    let config = deck_config("No Such Deck");
    assert_eq!(config.key, "");
    bits_eq(config.ante_scaling, 1.0, "unknown ante_scaling");
    assert_eq!(config.extra_hand_bonus, 1);
    assert_eq!(config.extra_discard_bonus, 0);
    assert_eq!(config.consumables, &[] as &[&str]);
    assert_eq!(config.vouchers, &[] as &[&str]);
    let _ = DeckConfig::default();
}

#[test]
fn the_finisher_reward_rule_holds_for_every_boss() {
    // The five finishers pay eight; every ordinary boss pays the usual five.
    for boss in all_bosses() {
        let want = if boss.is_finisher { FINISHER_REWARD } else { 5 };
        assert_eq!(
            reward_for(BlindKind::Boss, Some(boss)),
            want,
            "{}",
            boss.name
        );
    }
    assert_eq!(reward_for(BlindKind::Small, None), 3);
    assert_eq!(reward_for(BlindKind::Big, None), 4);
}
