//! The Tarot/Planet/Spectral registry, replayed against the Python original.
//!
//! The fixture is generated by `tools/gen_consumable_specs_fixture.py` from
//! `jimbot_sim.consumables.REGISTRY` and `jimbot_sim.consumable_data`.
//! `hand_levels` and the deck contents are asserted directly rather than
//! against log strings -- a spec that logs the right thing and moves the wrong
//! card must fail.

use std::rc::Rc;

use jimbot_sim::cards::{
    edition_of, enhancement_of, extra_chips_of, make_card, rank_of, seal_of, suit_of, Edition,
    Enhancement, Rank, Seal, Suit,
};
use jimbot_sim::consumables::{self, spec_or_panic};
use jimbot_sim::game::GameState;
use jimbot_sim::hands::HandType;
use jimbot_sim::jokers;

const FIXTURE: &str = include_str!("fixtures/consumable_specs.txt");

fn fields(line: &str) -> Vec<&str> {
    line.split('\t').collect()
}

/// A run with every pile emptied, so a test's deck is exactly what it built.
fn fresh() -> GameState {
    let mut game = GameState::new("CONSUMABLE", "Red Deck", 1);
    game.full_deck.clear();
    game.draw_pile.clear();
    game.hand.clear();
    game.discard_pile.clear();
    game
}

fn apply(name: &str, game: &mut GameState, cards: &[jimbot_sim::cards::CardRef]) {
    let spec = spec_or_panic(name);
    (spec.apply.expect("a registered consumable has an apply"))(game, cards);
}

#[test]
fn every_python_registry_card_is_registered() {
    let mut total: Option<usize> = None;
    let mut data_total: Option<usize> = None;
    let mut registry_names: Vec<String> = Vec::new();
    let mut data_names: Vec<String> = Vec::new();
    for line in FIXTURE.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let f = fields(line);
        match f[0] {
            "total" => total = Some(f[1].parse().unwrap()),
            "data_total" => data_total = Some(f[1].parse().unwrap()),
            "spec" => registry_names.push(f[1].to_string()),
            "data" => data_names.push(f[1].to_string()),
            other => panic!("unknown fixture record {:?}", other),
        }
    }
    let total = total.expect("fixture has a total record");
    let data_total = data_total.expect("fixture has a data_total record");

    let registered = consumables::all_specs().len();
    let missing: Vec<&str> = registry_names
        .iter()
        .map(String::as_str)
        .filter(|name| consumables::spec(name).is_none())
        .collect();
    let missing_from_data: Vec<&str> = data_names
        .iter()
        .map(String::as_str)
        .filter(|name| consumables::spec(name).is_none())
        .collect();
    if !missing.is_empty() {
        eprintln!(
            "consumable specs not translated ({}/{}): {}",
            missing.len(),
            total,
            missing.join(", ")
        );
    }
    if !missing_from_data.is_empty() {
        eprintln!(
            "consumable_data rows with no spec ({}/{}): {}",
            missing_from_data.len(),
            data_total,
            missing_from_data.join(", ")
        );
    }

    assert_eq!(registry_names.len(), total, "fixture replayed the wrong count");
    assert_eq!(registered, total, "registered {registered} of {total} consumables");
    assert!(missing.is_empty(), "unregistered consumables: {missing:?}");
    assert!(
        missing_from_data.is_empty(),
        "consumable_data rows with no spec: {missing_from_data:?}"
    );
    assert_eq!(
        jimbot_sim::consumable_data::CONSUMABLE_DATA.len(),
        data_total,
        "the data table has a different row count"
    );
}

#[test]
fn every_spec_field_matches_the_python() {
    let mut seen = 0usize;
    for line in FIXTURE.lines().filter(|l| l.starts_with("spec\t")) {
        let f = fields(line);
        let name = f[1];
        let spec = spec_or_panic(name);
        assert_eq!(spec.kind.set_name(), f[2], "{} kind", name);
        assert_eq!(spec.targets, f[3].parse::<i32>().unwrap(), "{} targets", name);
        let max = if f[4] == "-" {
            None
        } else {
            Some(f[4].parse::<i32>().unwrap())
        };
        assert_eq!(spec.max_targets, max, "{} max_targets", name);
        assert_eq!(spec.cost, f[5].parse::<i32>().unwrap(), "{} cost", name);
        assert_eq!(spec.apply.is_some(), f[6] == "1", "{} apply", name);
        assert_eq!(spec.text, f[7], "{} text", name);
        // `accepts` is `targets <= n <= max_targets`, max defaulting to targets.
        assert!(spec.accepts(spec.targets), "{} accepts its targets", name);
        let high = spec.max_targets.unwrap_or(spec.targets);
        assert!(!spec.accepts(high + 1), "{} refuses more than max", name);
        seen += 1;
    }
    assert!(seen > 0, "the fixture has no spec records");
}

#[test]
fn death_turns_the_left_card_into_the_right() {
    let mut game = fresh();
    let left = make_card(Rank::Two, Suit::Clubs);
    let right = make_card(Rank::King, Suit::Hearts);
    right.borrow_mut().enhancement = Enhancement::Mult;
    right.borrow_mut().seal = Seal::Gold;
    right.borrow_mut().edition = Edition::Foil;
    right.borrow_mut().extra_chips = 7;
    right.borrow_mut().played_this_ante = true;
    game.hand.push(left.clone());
    game.hand.push(right.clone());
    game.full_deck.push(left.clone());
    game.full_deck.push(right.clone());

    // Passed right-then-left: Death resolves "left" by hand position, not by the
    // order the caller selected them.
    apply("Death", &mut game, &[right.clone(), left.clone()]);

    assert_eq!(rank_of(&left), Rank::King);
    assert_eq!(suit_of(&left), Suit::Hearts);
    assert_eq!(enhancement_of(&left), Enhancement::Mult);
    assert_eq!(seal_of(&left), Seal::Gold);
    assert_eq!(edition_of(&left), Edition::Foil);
    assert_eq!(extra_chips_of(&left), 7);
    assert!(left.borrow().played_this_ante);
    // The right card is untouched.
    assert_eq!(rank_of(&right), Rank::King);
    assert_eq!(suit_of(&right), Suit::Hearts);
    assert_eq!(extra_chips_of(&right), 7);
    assert_eq!(suit_of(&left), suit_of(&right));
}

#[test]
fn death_uses_the_screen_position_not_the_selection_order() {
    // The same two cards, selected the other way, convert the other one.
    let mut game = fresh();
    let left = make_card(Rank::Two, Suit::Clubs);
    let right = make_card(Rank::Ace, Suit::Spades);
    game.hand.push(left.clone());
    game.hand.push(right.clone());
    apply("Death", &mut game, &[left.clone(), right.clone()]);
    assert_eq!(rank_of(&left), Rank::Ace);
    assert_eq!(rank_of(&right), Rank::Ace);
}

#[test]
fn hanged_man_destroys_both_from_every_pile() {
    let mut game = fresh();
    let a = make_card(Rank::Two, Suit::Clubs);
    let b = make_card(Rank::Three, Suit::Diamonds);
    let keep = make_card(Rank::Four, Suit::Spades);
    for card in [&a, &b] {
        game.full_deck.push(card.clone());
        game.draw_pile.push(card.clone());
        game.hand.push(card.clone());
        game.discard_pile.push(card.clone());
    }
    game.full_deck.push(keep.clone());
    game.hand.push(keep.clone());

    apply("The Hanged Man", &mut game, &[a.clone(), b.clone()]);

    assert_eq!(game.full_deck.len(), 1, "full_deck kept the wrong cards");
    assert_eq!(game.hand.len(), 1, "hand kept the wrong cards");
    assert!(game.draw_pile.is_empty(), "draw_pile retained a destroyed card");
    assert!(
        game.discard_pile.is_empty(),
        "discard_pile retained a destroyed card"
    );
    assert!(Rc::ptr_eq(&game.full_deck[0], &keep));
    assert!(Rc::ptr_eq(&game.hand[0], &keep));
}

#[test]
fn an_enhancement_tarot_enhances_the_selected_cards() {
    let mut game = fresh();
    let a = make_card(Rank::Two, Suit::Clubs);
    let b = make_card(Rank::Three, Suit::Clubs);
    game.add_card_to_hand(&a);
    game.add_card_to_hand(&b);

    apply("The Magician", &mut game, &[a.clone(), b.clone()]);

    assert_eq!(enhancement_of(&a), Enhancement::Lucky);
    assert_eq!(enhancement_of(&b), Enhancement::Lucky);
}

#[test]
fn a_seal_spectral_adds_its_seal() {
    let mut game = fresh();
    let card = make_card(Rank::Two, Suit::Clubs);
    game.add_card_to_hand(&card);

    apply("Talisman", &mut game, &[card.clone()]);

    assert_eq!(seal_of(&card), Seal::Gold);
}

#[test]
fn a_planet_levels_its_hand() {
    let mut game = fresh();
    let before = game.hand_levels.level(HandType::Pair);
    apply("Mercury", &mut game, &[]);
    assert_eq!(game.hand_levels.level(HandType::Pair), before + 1);
    // And only its own hand.
    assert_eq!(game.hand_levels.level(HandType::Flush), 1);
}

#[test]
fn black_hole_levels_every_hand() {
    let mut game = fresh();
    apply("Black Hole", &mut game, &[]);
    for hand in HandType::ALL {
        assert_eq!(game.hand_levels.level(hand), 2, "{} level", hand.label());
    }
}

#[test]
fn immolate_destroys_five_in_hand_and_pays() {
    let mut game = fresh();
    for index in 0..6 {
        let card = make_card(Rank::ALL[index], Suit::Clubs);
        game.add_card_to_hand(&card);
    }
    apply("Immolate", &mut game, &[]);
    assert_eq!(game.hand.len(), 1, "exactly one card should remain in hand");
    assert_eq!(game.full_deck.len(), 1, "the deck drops the same five");
    assert_eq!(game.money, 4 + 20);
}

#[test]
fn cryptid_makes_two_copies_into_the_hand() {
    let mut game = fresh();
    let card = make_card(Rank::King, Suit::Hearts);
    game.add_card_to_hand(&card);
    apply("Cryptid", &mut game, &[card.clone()]);
    assert_eq!(game.hand.len(), 3, "the original plus two copies");
    assert_eq!(game.full_deck.len(), 3);
    for copy in &game.hand {
        assert_eq!(rank_of(copy), Rank::King);
        assert_eq!(suit_of(copy), Suit::Hearts);
    }
}

#[test]
fn ankh_copies_one_joker_and_destroys_the_rest() {
    // A synthetic spec: this test is about Ankh's copy-and-destroy, not about
    // the joker registry, which another module owns.
    static JOKER: jokers::JokerSpec = jokers::JokerSpec {
        name: "Joker",
        ..jokers::JokerSpec::DEFAULT
    };
    let mut game = fresh();
    let a = jokers::make_ref(jokers::JokerInstance::new(&JOKER));
    let b = jokers::make_ref(jokers::JokerInstance::new(&JOKER));
    game.jokers.push(a.clone());
    game.jokers.push(b.clone());
    apply("Ankh", &mut game, &[]);
    // One survives, one is destroyed, one copy is added.
    assert_eq!(game.jokers.len(), 2);
    let survived_a = game.jokers.iter().filter(|j| Rc::ptr_eq(j, &a)).count();
    let survived_b = game.jokers.iter().filter(|j| Rc::ptr_eq(j, &b)).count();
    assert_eq!(survived_a + survived_b, 1, "exactly one original survives");
}

#[test]
fn ouija_makes_the_whole_hand_one_rank() {
    let mut game = fresh();
    let before = game.base_hand_size;
    let mut cards = Vec::new();
    for rank in [Rank::Two, Rank::Three, Rank::Four, Rank::Five] {
        let card = make_card(rank, Suit::Clubs);
        game.add_card_to_hand(&card);
        cards.push(card);
    }
    apply("Ouija", &mut game, &[]);
    let rank = rank_of(&cards[0]);
    for card in &cards {
        assert_eq!(rank_of(card), rank, "every card shares the drawn rank");
    }
    assert_eq!(game.base_hand_size, before - 1);
}

#[test]
fn familiar_swaps_one_card_for_three_enhanced_faces() {
    let mut game = fresh();
    for rank in [Rank::Two, Rank::Three, Rank::Four, Rank::Five] {
        let card = make_card(rank, Suit::Clubs);
        game.add_card_to_hand(&card);
    }
    apply("Familiar", &mut game, &[]);
    assert_eq!(game.hand.len(), 6, "one out, three in");
    let made: Vec<_> = game
        .hand
        .iter()
        .filter(|c| enhancement_of(c) != Enhancement::None)
        .collect();
    assert_eq!(made.len(), 3, "Familiar always enhances what it makes");
    for card in made {
        assert!(rank_of(card).is_face(), "Familiar makes face cards");
    }
}

#[test]
fn grim_makes_two_enhanced_aces() {
    let mut game = fresh();
    for rank in [Rank::Two, Rank::Three, Rank::Four] {
        let card = make_card(rank, Suit::Clubs);
        game.add_card_to_hand(&card);
    }
    apply("Grim", &mut game, &[]);
    assert_eq!(game.hand.len(), 4, "one out, two in");
    let made: Vec<_> = game
        .hand
        .iter()
        .filter(|c| enhancement_of(c) != Enhancement::None)
        .collect();
    assert_eq!(made.len(), 2);
    for card in made {
        assert_eq!(rank_of(card), Rank::Ace, "Grim makes Aces");
    }
}

#[test]
fn ectoplasm_negatives_a_joker_and_costs_a_growing_hand_size() {
    static JOKER: jokers::JokerSpec = jokers::JokerSpec {
        name: "Joker",
        ..jokers::JokerSpec::DEFAULT
    };
    let mut game = fresh();
    let joker = jokers::make_ref(jokers::JokerInstance::new(&JOKER));
    game.jokers.push(joker.clone());
    let before = game.base_hand_size;
    apply("Ectoplasm", &mut game, &[]);
    assert_eq!(joker.borrow().edition, Edition::Negative);
    assert_eq!(game.base_hand_size, before - 1);
    assert_eq!(game.ecto_minus, 2, "the cost climbs for the next use");
}

#[test]
fn sigil_makes_the_whole_hand_one_suit() {
    let mut game = fresh();
    let suits = [Suit::Clubs, Suit::Diamonds, Suit::Hearts, Suit::Spades];
    let mut cards = Vec::new();
    for suit in suits {
        let card = make_card(Rank::Two, suit);
        game.add_card_to_hand(&card);
        cards.push(card);
    }
    apply("Sigil", &mut game, &[]);
    let suit = suit_of(&cards[0]);
    for card in &cards {
        assert_eq!(suit_of(card), suit, "every card shares the drawn suit");
    }
}

#[test]
fn aura_never_adds_a_negative() {
    let mut game = fresh();
    let card = make_card(Rank::Two, Suit::Clubs);
    game.add_card_to_hand(&card);
    apply("Aura", &mut game, &[card.clone()]);
    assert_ne!(edition_of(&card), Edition::Negative);
}

#[test]
fn hex_polychromes_one_joker_and_destroys_the_rest() {
    static JOKER: jokers::JokerSpec = jokers::JokerSpec {
        name: "Joker",
        ..jokers::JokerSpec::DEFAULT
    };
    let mut game = fresh();
    for _ in 0..3 {
        game.jokers
            .push(jokers::make_ref(jokers::JokerInstance::new(&JOKER)));
    }
    apply("Hex", &mut game, &[]);
    assert_eq!(game.jokers.len(), 1, "Hex destroys every joker but one");
    assert_eq!(game.jokers[0].borrow().edition, Edition::Polychrome);
}
