//! Replay the Python data modules' own tables, row for row.
//!
//! The fixtures are generated by `tools/gen_joker_data_rs.py` and
//! `tools/gen_consumable_data_rs.py` from the imported Python originals, so a
//! stale Rust table -- one edited by hand or generated from an older Python
//! revision -- fails here instead of silently offering the wrong joker in the
//! shop. Every field is compared, and the totals are checked so a table that
//! merely drops a row cannot pass.

use jimbot_sim::consumable_data as cd;
use jimbot_sim::joker_data as jd;

const JOKER_FIXTURE: &str = include_str!("fixtures/joker_data.txt");
const CONSUMABLE_FIXTURE: &str = include_str!("fixtures/consumable_data.txt");

fn fields(line: &str) -> Vec<&str> {
    line.split('\t').collect()
}

#[test]
fn joker_rows_match_the_python_table() {
    let mut seen = 0usize;
    let mut total: Option<usize> = None;
    for (lineno, line) in JOKER_FIXTURE.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let f = fields(line);
        match f[0] {
            "total" => total = Some(f[1].parse().unwrap()),
            "joker" => {
                let name = f[1];
                let row = jd::joker_row(name)
                    .unwrap_or_else(|| panic!("missing joker {:?} (line {})", name, lineno + 1));
                assert_eq!(row.name, name, "line {}", lineno + 1);
                assert_eq!(row.key, f[2], "{} key", name);
                assert_eq!(row.rarity, f[3].parse::<u8>().unwrap(), "{} rarity", name);
                assert_eq!(row.order, f[4].parse::<i32>().unwrap(), "{} order", name);
                assert_eq!(row.unlocked, f[5] == "True", "{} unlocked", name);
                assert_eq!(row.enhancement_gate, f[6], "{} enhancement_gate", name);
                assert_eq!(row.no_flag, f[7], "{} no_flag", name);
                assert_eq!(row.yes_flag, f[8], "{} yes_flag", name);
                assert_eq!(row.eternal_ok, f[9] == "True", "{} eternal_ok", name);
                assert_eq!(row.perishable_ok, f[10] == "True", "{} perishable_ok", name);
                // The key index must agree with the name index.
                let by_key = jd::joker_row_by_key(row.key)
                    .unwrap_or_else(|| panic!("missing joker key {:?}", row.key));
                assert_eq!(by_key.name, name, "{} key index", name);
                seen += 1;
            }
            other => panic!("unknown fixture record {:?} at line {}", other, lineno + 1),
        }
    }

    let total = total.expect("fixture has no total record");
    assert_eq!(seen, total, "fixture replayed {seen} of {total} jokers");
    assert_eq!(
        jd::JOKER_DATA.len(),
        total,
        "table has a different row count"
    );

    // The shop draws an index into the pool, so per-rarity order is load-bearing.
    for rarity in 1..=4u8 {
        let pool = jd::pool_for_rarity(rarity);
        let keys = jd::pool_for_rarity_keys(rarity);
        assert_eq!(pool.len(), keys.len());
        for (i, row) in pool.iter().enumerate() {
            assert_eq!(row.rarity, rarity, "{} is in the wrong pool", row.name);
            assert_eq!(keys[i], row.key, "keys diverge from rows");
            if i > 0 {
                assert!(
                    pool[i - 1].order <= row.order,
                    "rarity {rarity} pool is out of order: {} before {}",
                    pool[i - 1].name,
                    row.name
                );
            }
        }
    }
}

#[test]
fn consumable_rows_match_the_python_table() {
    let mut seen = 0usize;
    let mut total: Option<usize> = None;
    let mut fixture_sets: Vec<(String, Vec<&str>)> = Vec::new();
    for (lineno, line) in CONSUMABLE_FIXTURE.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let f = fields(line);
        match f[0] {
            "total" => total = Some(f[1].parse().unwrap()),
            "consumable" => {
                let (set, key, name) = (f[1], f[2], f[3]);
                let row = cd::consumable_row(name).unwrap_or_else(|| {
                    panic!("missing consumable {:?} (line {})", name, lineno + 1)
                });
                assert_eq!(row.set, set, "{} set", name);
                assert_eq!(row.key, key, "{} key", name);
                assert_eq!(row.name, name, "line {}", lineno + 1);
                assert_eq!(row.order, f[4].parse::<i32>().unwrap(), "{} order", name);
                assert_eq!(row.softlock, f[5] == "True", "{} softlock", name);
                assert_eq!(row.hand_type, f[6], "{} hand_type", name);
                let by_key = cd::consumable_row_by_key(row.key)
                    .unwrap_or_else(|| panic!("missing consumable key {:?}", row.key));
                assert_eq!(by_key.name, name, "{} key index", name);
                match fixture_sets.iter_mut().find(|(s, _)| s.as_str() == set) {
                    Some((_, keys)) => keys.push(key),
                    None => fixture_sets.push((set.to_string(), vec![key])),
                }
                seen += 1;
            }
            other => panic!("unknown fixture record {:?} at line {}", other, lineno + 1),
        }
    }

    let total = total.expect("fixture has no total record");
    assert_eq!(
        seen, total,
        "fixture replayed {seen} of {total} consumables"
    );
    assert_eq!(
        cd::CONSUMABLE_DATA.len(),
        total,
        "table has a different row count"
    );

    // Sets come in Tarot, Planet, Spectral order, each in its own pool order.
    let fixture_order: Vec<&str> = fixture_sets.iter().map(|(s, _)| s.as_str()).collect();
    assert_eq!(fixture_order, vec!["Tarot", "Planet", "Spectral"]);
    for (set, keys) in &fixture_sets {
        let got: Vec<&str> = cd::consumable_rows_for_set(set)
            .iter()
            .map(|row| row.key)
            .collect();
        assert_eq!(&got, keys, "{set} pool order");
    }

    assert_eq!(cd::EXCLUDED_FROM_POOLS, ["Black Hole", "The Soul"]);
}
