//! The joker registry: how much of it is translated, and that the translated
//! hooks behave.
//!
//! The fixture `fixtures/joker_specs.txt` is generated by
//! `tools/gen_joker_specs_fixture.py` straight off `jimbot_sim.jokers.REGISTRY`
//! (one entry per `register(...)` call) and off `jimbot_sim.joker_data`, which
//! has one row per joker the game ships. The first test compares the two counts
//! and, if the Rust table is short, *names every joker that is missing* -- a gap
//! in this registry is the failure mode the port has to avoid, because a joker
//! with no spec scores nothing and looks exactly like a joker that does nothing.
//!
//! The rest exercise the mechanics-heavy hooks through the same entry points the
//! scoring pipeline uses: `scoring::score_hand`, `scoring::held_triggers`, and
//! the round hooks the state machine calls.

use std::collections::BTreeSet;

use jimbot_sim::cards::{make_card, Rank, Suit};
use jimbot_sim::game::GameState;
use jimbot_sim::jokers::{self, Rarity};
use jimbot_sim::scoring;

const FIXTURE: &str = include_str!("fixtures/joker_specs.txt");

struct Row {
    name: String,
    rarity: Rarity,
    cost: i32,
}

fn rarity_from(name: &str) -> Rarity {
    match name {
        "COMMON" => Rarity::Common,
        "UNCOMMON" => Rarity::Uncommon,
        "RARE" => Rarity::Rare,
        "LEGENDARY" => Rarity::Legendary,
        other => panic!("unknown rarity {:?} in the fixture", other),
    }
}

/// `(registry_total, game_total, rows)`.
fn fixture_rows() -> (usize, usize, Vec<Row>) {
    let mut registry_total = None;
    let mut game_total = None;
    let mut rows = Vec::new();
    for line in FIXTURE.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        match f[0] {
            "registry" => registry_total = Some(f[1].parse().unwrap()),
            "game" => game_total = Some(f[1].parse().unwrap()),
            "joker" => rows.push(Row {
                name: f[1].to_string(),
                rarity: rarity_from(f[2]),
                cost: f[3].parse().unwrap(),
            }),
            other => panic!("unknown fixture record {:?}", other),
        }
    }
    (
        registry_total.expect("fixture has no registry total"),
        game_total.expect("fixture has no game total"),
        rows,
    )
}

#[test]
fn the_registry_reaches_every_joker_the_python_registers() {
    let (registry_total, game_total, rows) = fixture_rows();
    let have: BTreeSet<&str> = jokers::all_specs().iter().map(|s| s.name).collect();

    let missing: Vec<&str> = rows
        .iter()
        .filter(|r| !have.contains(r.name.as_str()))
        .map(|r| r.name.as_str())
        .collect();
    assert!(
        missing.is_empty(),
        "{} of the Python registry's {} jokers are not registered (the game ships {}): {:?}",
        missing.len(),
        registry_total,
        game_total,
        missing,
    );
    assert_eq!(
        jokers::all_specs().len(),
        registry_total,
        "Rust registers {} specs but the Python registers {}",
        jokers::all_specs().len(),
        registry_total,
    );

    // And no strays: a spec with no Python counterpart is a joker the game does
    // not have, which the shop could never offer.
    let fixture_names: BTreeSet<&str> = rows.iter().map(|r| r.name.as_str()).collect();
    for spec in jokers::all_specs() {
        assert!(
            fixture_names.contains(spec.name),
            "spec {:?} is not in the Python registry",
            spec.name,
        );
    }
}

#[test]
fn costs_and_rarities_match_the_python_registry() {
    let (_, _, rows) = fixture_rows();
    assert_eq!(jokers::all_specs().len(), rows.len());
    for row in &rows {
        let spec = jokers::spec(&row.name)
            .unwrap_or_else(|| panic!("no spec named {:?} is registered", row.name));
        assert_eq!(spec.cost, row.cost, "{} cost", row.name);
        assert_eq!(spec.rarity, row.rarity, "{} rarity", row.name);
    }
}


#[test]
fn a_scaling_counter_grows_across_hands() {
    let mut game = GameState::new("SEED0000", "Red Deck", 1);
    let green = jokers::make("Green Joker");
    game.jokers = vec![green.clone()];
    let played = vec![
        make_card(Rank::Ace, Suit::Spades),
        make_card(Rank::Ace, Suit::Hearts),
    ];
    let result = game.evaluate_selection(&played);

    // Green Joker increments while the last played card is scoring -- the
    // `update_before_scoring` branch -- so the very first hand pays its NEW
    // value: Pair 10 x 2, two Aces 22 chips, and +1 mult.
    let ctx = scoring::score_hand(&mut game, &result, &played, &[]);
    assert_eq!(green.borrow().counter, 1.0);
    assert_eq!(ctx.chips, 32.0);
    assert_eq!(ctx.mult, 3.0);

    // And it goes on growing: the second hand pays +2.
    let ctx = scoring::score_hand(&mut game, &result, &played, &[]);
    assert_eq!(green.borrow().counter, 2.0);
    assert_eq!(ctx.mult, 4.0);
}

#[test]
fn a_decaying_joker_scores_its_old_value_and_is_then_eaten() {
    let mut game = GameState::new("SEED0000", "Red Deck", 1);
    let cream = jokers::make("Ice Cream");
    game.jokers = vec![cream.clone()];
    let played = vec![
        make_card(Rank::Ace, Suit::Spades),
        make_card(Rank::Ace, Suit::Hearts),
    ];
    let result = game.evaluate_selection(&played);

    // Ice Cream grows under `context.after`, so this hand scores the 100 it
    // started with and only then melts to 95.
    let ctx = scoring::score_hand(&mut game, &result, &played, &[]);
    assert_eq!(ctx.chips, 32.0 + 100.0);
    assert_eq!(cream.borrow().counter, 95.0);

    // Popcorn is eaten rather than floored: a Popcorn on four mult with four to
    // lose is gone, not reduced to zero.
    let popcorn = jokers::make("Popcorn");
    popcorn.borrow_mut().counter = 4.0;
    game.jokers = vec![popcorn.clone()];
    let hook = jokers::spec("Popcorn").unwrap().round_end.unwrap();
    hook(&popcorn, &mut game);
    assert!(
        game.jokers.is_empty(),
        "a Popcorn at 4 with -4 to lose should be destroyed, not floored",
    );
}

#[test]
fn a_copier_runs_the_copied_jokers_effect() {
    let mut game = GameState::new("SEED0000", "Red Deck", 1);
    game.jokers = vec![jokers::make("Blueprint"), jokers::make("Joker")];
    let played = vec![
        make_card(Rank::Ace, Suit::Spades),
        make_card(Rank::Ace, Suit::Hearts),
    ];
    let result = game.evaluate_selection(&played);
    let ctx = scoring::score_hand(&mut game, &result, &played, &[]);
    // The Joker adds 4 mult, and the Blueprint to its left copies that ability
    // and adds 4 again: Pair 2 + 4 + 4.
    assert_eq!(ctx.mult, 10.0);

    // Brainstorm copies the leftmost joker instead, so with the Joker first it
    // copies it too.
    let mut game = GameState::new("SEED0000", "Red Deck", 1);
    game.jokers = vec![jokers::make("Joker"), jokers::make("Brainstorm")];
    let result = game.evaluate_selection(&played);
    let ctx = scoring::score_hand(&mut game, &result, &played, &[]);
    assert_eq!(ctx.mult, 10.0);
}

#[test]
fn a_retrigger_repeats_through_a_copying_mime() {
    let mut game = GameState::new("SEED0000", "Red Deck", 1);
    let card = make_card(Rank::Ace, Suit::Spades);
    assert_eq!(scoring::held_triggers(&mut game, &card), 1);

    game.jokers = vec![jokers::make("Mime")];
    assert_eq!(scoring::held_triggers(&mut game, &card), 2);

    // A Blueprint copying a Mime retriggers too -- held_triggers goes through
    // effective_specs, so the copier has the Mime's retrigger to offer.
    game.jokers = vec![jokers::make("Blueprint"), jokers::make("Mime")];
    assert_eq!(scoring::held_triggers(&mut game, &card), 3);
}

#[test]
fn a_scored_hook_fires_on_every_scoring_card() {
    let mut game = GameState::new("SEED0000", "Red Deck", 1);
    game.jokers = vec![jokers::make("Scary Face")];
    let played = vec![
        make_card(Rank::King, Suit::Spades),
        make_card(Rank::King, Suit::Hearts),
    ];
    let result = game.evaluate_selection(&played);
    let ctx = scoring::score_hand(&mut game, &result, &played, &[]);
    // Pair 10 chips; each King scores its 10; Scary Face adds 30 on each face
    // card that scores.
    assert_eq!(ctx.chips, 10.0 + 10.0 + 10.0 + 30.0 + 30.0);
    assert_eq!(ctx.mult, 2.0);
}

#[test]
fn a_round_end_joker_acts_when_the_round_closes() {
    let mut game = GameState::new("SEED0000", "Red Deck", 1);
    let egg = jokers::make("Egg");
    game.jokers = vec![egg.clone()];
    let hook = jokers::spec("Egg").unwrap().round_end.unwrap();
    hook(&egg, &mut game);
    assert_eq!(egg.borrow().extra_sell_value, 3.0);

    // And the cash-out rows pay at the end of the round: Golden Joker's $4.
    let golden = jokers::make("Golden Joker");
    let before = game.money;
    let hook = jokers::spec("Golden Joker").unwrap().round_money.unwrap();
    hook(&golden, &mut game);
    assert_eq!(game.money, before + 4);
}

