//! Replay the Python simulator's own random stream, draw for draw.
//!
//! The fixture is generated by `tools/gen_rng_fixture.py` against the Python
//! original. `%.17g` round-trips a double exactly, so the comparison is on bits
//! rather than on printed digits -- which is the only test that separates
//! replication from coincidence.

use jimbot_sim::rng::{pseudohash, PessimisticRng, RunRng, TW223};

const FIXTURE: &str = include_str!("fixtures/rng_stream.txt");

fn bits_eq(got: f64, want: f64, what: &str) {
    assert_eq!(
        got.to_bits(),
        want.to_bits(),
        "{}: got {:?} ({:016x}) want {:?} ({:016x})",
        what,
        got,
        got.to_bits(),
        want,
        want.to_bits()
    );
}

#[test]
fn the_stream_matches_the_python_simulator() {
    let mut checked = 0usize;
    for (lineno, line) in FIXTURE.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        match f[0] {
            "hash" => {
                bits_eq(pseudohash(f[1]), f[2].parse().unwrap(), line);
                checked += 1;
            }
            "pseudoseed" => {
                let seed = f[1];
                let key = f[2];
                let index: usize = f[3].parse().unwrap();
                let want: f64 = f[4].parse().unwrap();
                let mut rng = RunRng::new(seed);
                let mut got = 0.0;
                for _ in 0..=index {
                    got = rng.pseudoseed(key);
                }
                bits_eq(got, want, line);
                checked += 1;
            }
            "draw" => {
                let seed = f[1];
                let key = f[2];
                let index: usize = f[3].parse().unwrap();
                let want: f64 = f[4].parse().unwrap();
                let mut rng = RunRng::new(seed);
                let mut got = 0.0;
                for _ in 0..=index {
                    got = rng.pseudorandom(key, None, None);
                }
                bits_eq(got, want, line);
                checked += 1;
            }
            "int" => {
                let seed = f[1];
                let key = f[2];
                let index: usize = f[3].parse().unwrap();
                let want: i64 = f[4].parse().unwrap();
                let mut rng = RunRng::new(seed);
                let mut got = 0i64;
                for _ in 0..=index {
                    got = rng.pseudorandom(key, Some(1.0), Some(10.0)) as i64;
                }
                assert_eq!(got, want, "{}", line);
                checked += 1;
            }
            "live" => {
                let seed = f[1];
                let index: usize = f[2].parse().unwrap();
                let want: f64 = f[3].parse().unwrap();
                let mut rng = RunRng::new(seed);
                rng.seeded("first");
                let mut got = 0.0;
                for _ in 0..=index {
                    got = rng.math_random(None, None);
                }
                bits_eq(got, want, line);
                checked += 1;
            }
            "livemix" => {
                // A named draw, then a bare one, three times over. `live` must
                // advance through each named draw, because Python's `seeded`
                // returns `self.live` itself. The `live` records above cannot
                // see this: they never make a named draw in between, so a port
                // that stored a clone taken *before* the draw passed them while
                // `live` sat one draw behind -- which is how the first shop's
                // Buffoon pack came out `_2` where the game rolls `_1`.
                let mut rng = RunRng::new(f[1]);
                let key = f[2];
                let want: Vec<f64> = f[3].split(',').map(|s| s.parse().unwrap()).collect();
                let mut got: Vec<f64> = Vec::new();
                rng.seeded(key);
                rng.pseudorandom(key, None, None);
                got.push(rng.math_random(None, None));
                rng.pseudorandom(key, None, None);
                got.push(rng.math_random(None, None));
                rng.random_element_index(5, key);
                got.push(rng.math_random(None, None));
                assert_eq!(got.len(), want.len(), "{}", line);
                for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
                    bits_eq(*g, *w, &format!("{} [{}]", line, i));
                }
                checked += 1;
            }
            "pessimistic" => {
                // The pessimistic generator's branches. `low > high` returns
                // `high`; the port's first version returned `low` either way
                // because the guard and both arms said the same thing, and no
                // record reached it until a preview comparison did.
                let low = if f[1] == "-" {
                    None
                } else {
                    Some(f[1].parse::<f64>().unwrap())
                };
                let high = if f[2] == "-" {
                    None
                } else {
                    Some(f[2].parse::<f64>().unwrap())
                };
                let want: f64 = f[3].parse().unwrap();
                let got = PessimisticRng::pseudorandom(low, high);
                bits_eq(got, want, line);
                checked += 1;
            }
            "shuffle" => {
                let seed = f[1];
                let n: usize = f[2].parse().unwrap();
                let want: Vec<usize> = f[3].split(',').map(|s| s.parse().unwrap()).collect();
                let mut rng = RunRng::new(seed);
                let mut items: Vec<usize> = (0..n).collect();
                rng.shuffle(&mut items, "shuffle");
                assert_eq!(items, want, "{}", line);
                checked += 1;
            }
            "tw223" => {
                let seed: f64 = f[1].parse().unwrap();
                let index: usize = f[2].parse().unwrap();
                let want: f64 = f[3].parse().unwrap();
                let mut rng = TW223::new(seed);
                let mut got = 0.0;
                for _ in 0..=index {
                    got = rng.random(None, None);
                }
                bits_eq(got, want, line);
                checked += 1;
            }
            "tw223int" => {
                let seed: f64 = f[1].parse().unwrap();
                let index: usize = f[2].parse().unwrap();
                let want: i64 = f[3].parse().unwrap();
                let mut rng = TW223::new(seed);
                let mut got = 0i64;
                for _ in 0..=index {
                    got = rng.random(Some(1.0), Some(20.0)) as i64;
                }
                assert_eq!(got, want, "{}", line);
                checked += 1;
            }
            other => panic!("unknown fixture record {:?} at line {}", other, lineno + 1),
        }
    }
    assert!(checked > 2000, "fixture only exercised {} records", checked);
}
