//! Replay the Python simulator's scoring pipeline, glass shattering and held
//! triggers.
//!
//! The fixture is generated by `tools/gen_scoring_fixture.py`. Chips, mult and the
//! expected money are written with `%.17g`, so the comparison is on bits rather
//! than printed digits. Cases whose jokers are not in the Rust registry yet are
//! recorded but skipped, and the skip counts are asserted so the coverage gap is
//! visible rather than silent.

use std::collections::BTreeMap;

use rumbot_sim::cards::{make_card, uid_of, CardRef, Edition, Enhancement, Rank, Seal, Suit};
use rumbot_sim::game::GameState;
use rumbot_sim::hands::HandLevels;
use rumbot_sim::jokers::{self, JokerInstance, JokerRef};
use rumbot_sim::rng::RunRng;
use rumbot_sim::scoring::{held_triggers, score_hand, shattered_glass};
use rumbot_sim::shop_pool::{self, PackCard};

const FIXTURE: &str = include_str!("fixtures/scoring.txt");
const EMPTY: &[&str] = &[];

fn bits_eq(got: f64, want: f64, what: &str) {
    assert_eq!(
        got.to_bits(),
        want.to_bits(),
        "{}: got {:?} ({:016x}) want {:?} ({:016x})",
        what,
        got,
        got.to_bits(),
        want,
        want.to_bits()
    );
}

fn enhancement(name: &str) -> Enhancement {
    match name {
        "none" => Enhancement::None,
        "bonus" => Enhancement::Bonus,
        "mult" => Enhancement::Mult,
        "wild" => Enhancement::Wild,
        "glass" => Enhancement::Glass,
        "steel" => Enhancement::Steel,
        "stone" => Enhancement::Stone,
        "gold" => Enhancement::Gold,
        "lucky" => Enhancement::Lucky,
        other => panic!("unknown enhancement {:?}", other),
    }
}

fn edition(name: &str) -> Edition {
    match name {
        "none" => Edition::None,
        "foil" => Edition::Foil,
        "holo" => Edition::Holographic,
        "polychrome" => Edition::Polychrome,
        "negative" => Edition::Negative,
        other => panic!("unknown edition {:?}", other),
    }
}

fn seal(name: &str) -> Seal {
    match name {
        "none" => Seal::None,
        "gold" => Seal::Gold,
        "red" => Seal::Red,
        "blue" => Seal::Blue,
        "purple" => Seal::Purple,
        other => panic!("unknown seal {:?}", other),
    }
}

/// `rank:suit:enhancement:edition:seal:debuffed`.
fn parse_card(spec: &str) -> CardRef {
    let f: Vec<&str> = spec.split(':').collect();
    assert_eq!(f.len(), 6, "card spec {:?}", spec);
    let card = make_card(
        Rank::from_code(f[0]).expect("rank"),
        Suit::from_code(f[1]).expect("suit"),
    );
    {
        let mut c = card.borrow_mut();
        c.enhancement = enhancement(f[2]);
        c.edition = edition(f[3]);
        c.seal = seal(f[4]);
        c.debuffed = f[5] == "1";
    }
    card
}

fn parse_cards(field: &str) -> Vec<CardRef> {
    if field == "-" {
        Vec::new()
    } else {
        field.split('|').map(parse_card).collect()
    }
}

fn parse_positions(field: &str) -> Vec<usize> {
    if field == "-" {
        Vec::new()
    } else {
        field.split(',').map(|s| s.parse().unwrap()).collect()
    }
}

/// `name:counter:secondary:edition:debuffed`, or `-` for none.
///
/// Returns `Err(name)` at the first joker the Rust registry does not carry, which
/// is how a case is skipped.
fn parse_jokers(field: &str) -> Result<Vec<JokerRef>, String> {
    if field == "-" {
        return Ok(Vec::new());
    }
    let mut out = Vec::new();
    for spec in field.split('|') {
        let f: Vec<&str> = spec.split(':').collect();
        assert_eq!(f.len(), 5, "joker spec {:?}", spec);
        let spec = jokers::spec(f[0]).ok_or_else(|| f[0].to_string())?;
        let joker = jokers::make_ref(JokerInstance::new(spec));
        {
            let mut j = joker.borrow_mut();
            j.counter = f[1].parse().unwrap();
            j.secondary = f[2].parse().unwrap();
            j.edition = edition(f[3]);
            j.debuffed = f[4] == "1";
        }
        out.push(joker);
    }
    Ok(out)
}

fn build_game(seed: &str, deck: &str, stake: i32, jokers: Vec<JokerRef>, money: i32) -> GameState {
    let mut game = GameState::new(seed, deck, stake);
    game.rng = RunRng::new(seed);
    game.hand_levels = HandLevels::new();
    game.jokers = jokers;
    game.consumables.clear();
    game.vouchers.clear();
    game.blind = None;
    game.money = money;
    game
}

fn positions_of(scoring: &[CardRef], from: &[CardRef]) -> Vec<usize> {
    from.iter()
        .enumerate()
        .filter(|(_, card)| scoring.iter().any(|s| uid_of(s) == uid_of(card)))
        .map(|(i, _)| i)
        .collect()
}

fn parse_list(field: &str) -> Vec<&str> {
    if field == "-" {
        Vec::new()
    } else {
        field.split(',').collect()
    }
}

fn packcard_str(card: &PackCard) -> String {
    if card.set == "Playing" {
        format!(
            "P:{}:{}:{}:{}:{}",
            card.rank.as_deref().expect("rank"),
            card.suit.as_deref().expect("suit"),
            card.enhancement.as_deref().unwrap_or("-"),
            card.edition.unwrap_or("none"),
            card.seal.as_deref().unwrap_or("-")
        )
    } else if card.set == "Joker" {
        format!(
            "J:{}:{}:{}:{}:{}",
            card.key.as_deref().unwrap_or("-"),
            card.edition.unwrap_or("none"),
            card.eternal as i32,
            card.perishable as i32,
            card.rental as i32
        )
    } else {
        format!("C:{}:{}", card.set, card.key.as_deref().unwrap_or("-"))
    }
}

#[test]
fn the_scoring_pipeline_matches_the_python_simulator() {
    let mut score_total = 0usize;
    let mut score_checked = 0usize;
    let mut score_pess_skipped = 0usize;
    let mut score_joker_skipped = 0usize;
    let mut held_total = 0usize;
    let mut held_checked = 0usize;
    let mut held_joker_skipped = 0usize;
    let mut glass_checked = 0usize;
    let mut pool_checked = 0usize;
    let mut joker_skips: BTreeMap<String, Vec<usize>> = BTreeMap::new();

    for (lineno, line) in FIXTURE.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        let at = format!("line {}", lineno + 1);
        match f[0] {
            "score" => {
                score_total += 1;
                if f[7] == "pess" {
                    // GameState has no preview/pessimistic RNG mode ported yet;
                    // see GameState._preview and `PessimisticRng`.
                    score_pess_skipped += 1;
                    continue;
                }
                let jokers = match parse_jokers(f[6]) {
                    Ok(jokers) => jokers,
                    Err(name) => {
                        score_joker_skipped += 1;
                        joker_skips.entry(name).or_default().push(lineno + 1);
                        continue;
                    }
                };
                let played = parse_cards(f[4]);
                let held = parse_cards(f[5]);
                let mut game = build_game(f[1], f[2], f[3].parse().unwrap(), jokers, 4);
                let result = game.evaluate_selection(&played);
                assert_eq!(
                    positions_of(&result.scoring, &played),
                    parse_positions(f[8]),
                    "{}: scoring positions",
                    at
                );
                let score = score_hand(&mut game, &result, &played, &held);
                bits_eq(score.chips, f[9].parse().unwrap(), &format!("{} chips", at));
                bits_eq(score.mult, f[10].parse().unwrap(), &format!("{} mult", at));
                assert_eq!(score.score(), f[11].parse::<i64>().unwrap(), "{} score", at);
                assert_eq!(
                    score.money_gained,
                    f[12].parse::<i32>().unwrap(),
                    "{} money_gained",
                    at
                );
                assert_eq!(
                    score.lucky_rolls,
                    f[13].parse::<i32>().unwrap(),
                    "{} lucky_rolls",
                    at
                );
                assert_eq!(
                    score.chance_paid,
                    f[14].parse::<i32>().unwrap(),
                    "{} chance_paid",
                    at
                );
                bits_eq(
                    score.chance_expected,
                    f[15].parse().unwrap(),
                    &format!("{} chance_expected", at),
                );
                score_checked += 1;
            }
            "held" => {
                held_total += 1;
                let jokers = match parse_jokers(f[3]) {
                    Ok(jokers) => jokers,
                    Err(name) => {
                        held_joker_skipped += 1;
                        joker_skips.entry(name).or_default().push(lineno + 1);
                        continue;
                    }
                };
                let card = parse_card(f[2]);
                let mut game = build_game(f[1], "Red Deck", 1, jokers, 4);
                assert_eq!(
                    held_triggers(&mut game, &card),
                    f[4].parse::<i32>().unwrap(),
                    "{}: held triggers",
                    at
                );
                held_checked += 1;
            }
            "glass" => {
                let cards = parse_cards(f[2]);
                let mut game = build_game(f[1], "Red Deck", 1, Vec::new(), 4);
                let broken = shattered_glass(&mut game, &cards);
                assert_eq!(
                    positions_of(&broken, &cards),
                    parse_positions(f[3]),
                    "{}: shattered glass",
                    at
                );
                glass_checked += 1;
            }
            "rarity" => {
                let mut rng = RunRng::new(f[1]);
                let got = shop_pool::roll_rarity(&mut rng, f[2].parse().unwrap(), f[3]);
                assert_eq!(got, f[4].parse::<u8>().unwrap(), "{}: roll_rarity", at);
                pool_checked += 1;
            }
            "joker" => {
                let mut rng = RunRng::new(f[1]);
                let owned = parse_list(f[4]);
                let seen = parse_list(f[5]);
                let flags = parse_list(f[6]);
                let rarity = if f[8] == "-" {
                    None
                } else {
                    Some(f[8].parse::<u8>().unwrap())
                };
                let got = shop_pool::draw_joker(
                    &mut rng,
                    f[2].parse().unwrap(),
                    &owned,
                    &seen,
                    f[7] == "1",
                    rarity,
                    &flags,
                    f[3],
                );
                assert_eq!(got, f[9], "{}: draw_joker", at);
                pool_checked += 1;
            }
            "slot" => {
                let mut rng = RunRng::new(f[1]);
                let got = shop_pool::roll_slot_type(&mut rng, f[2].parse().unwrap(), None);
                assert_eq!(got, f[3], "{}: roll_slot_type", at);
                pool_checked += 1;
            }
            "shopcard" => {
                let mut rng = RunRng::new(f[1]);
                let owned = parse_list(f[3]);
                let seen = parse_list(f[4]);
                let flags = parse_list(f[5]);
                let played = parse_list(f[6]);
                let (kind, key) = shop_pool::draw_shop_card(
                    &mut rng,
                    f[2].parse().unwrap(),
                    None,
                    &owned,
                    &seen,
                    false,
                    &flags,
                    &played,
                );
                assert_eq!(kind, f[7], "{}: shop card kind", at);
                assert_eq!(key, f[8], "{}: shop card key", at);
                pool_checked += 1;
            }
            "consumable" => {
                let mut rng = RunRng::new(f[1]);
                let played = parse_list(f[5]);
                let seen = parse_list(f[6]);
                let got = shop_pool::draw_consumable(
                    &mut rng,
                    f[2],
                    f[3].parse().unwrap(),
                    &played,
                    &seen,
                    f[7] == "1",
                    f[4],
                );
                assert_eq!(got, f[8], "{}: draw_consumable", at);
                pool_checked += 1;
            }
            "tag" => {
                let mut rng = RunRng::new(f[1]);
                let got =
                    shop_pool::draw_tag(&mut rng, f[2].parse().unwrap(), None::<&[&str]>, f[3]);
                assert_eq!(got, f[4], "{}: draw_tag", at);
                pool_checked += 1;
            }
            "voucher" => {
                let mut rng = RunRng::new(f[1]);
                let redeemed = parse_list(f[3]);
                let on_offer = parse_list(f[4]);
                let got = shop_pool::draw_voucher(
                    &mut rng,
                    f[2].parse().unwrap(),
                    &redeemed,
                    &on_offer,
                    f[5] == "1",
                );
                assert_eq!(got, f[6], "{}: draw_voucher", at);
                pool_checked += 1;
            }
            "edition" => {
                let mut rng = RunRng::new(f[1]);
                let got = shop_pool::poll_edition(
                    &mut rng,
                    f[2],
                    f[3].parse().unwrap(),
                    f[4] == "1",
                    f[5].parse().unwrap(),
                    f[6] == "1",
                );
                assert_eq!(got, f[7], "{}: poll_edition", at);
                pool_checked += 1;
            }
            "pack" => {
                let mut rng = RunRng::new(f[1]);
                rng.seeded("prime");
                let entry =
                    shop_pool::draw_pack(&mut rng, f[2].parse().unwrap(), f[3] == "1", "shop_pack");
                assert_eq!(entry.key, f[4], "{}: draw_pack", at);
                pool_checked += 1;
            }
            "stickers" => {
                let mut rng = RunRng::new(f[1]);
                let name = if f[7] == "-" { None } else { Some(f[7]) };
                let poll = shop_pool::poll_stickers(
                    &mut rng,
                    f[2].parse().unwrap(),
                    f[3] == "1",
                    f[4] == "1",
                    f[5] == "1",
                    f[6] == "1",
                    name,
                );
                assert_eq!(poll.eternal, f[8] == "1", "{}: sticker eternal", at);
                assert_eq!(poll.perishable, f[9] == "1", "{}: sticker perishable", at);
                assert_eq!(poll.rental, f[10] == "1", "{}: sticker rental", at);
                pool_checked += 1;
            }
            "packitems" => {
                let mut rng = RunRng::new(f[1]);
                let cards: i32 = f[3].parse().unwrap();
                let ante: i32 = f[4].parse().unwrap();
                let contents = shop_pool::pack_contents(
                    &mut rng, f[2], cards, ante, EMPTY, EMPTY, false, EMPTY, EMPTY, EMPTY, false,
                    false, false, false, None, None, 1.0,
                );
                let got: Vec<String> = contents.iter().map(packcard_str).collect();
                assert_eq!(got.join(","), f[5], "{}: pack contents", at);
                pool_checked += 1;
            }

            other => panic!("line {}: unknown fixture line kind {:?}", lineno + 1, other),
        }
    }

    if !joker_skips.is_empty() {
        eprintln!(
            "scoring fixture: {} case(s) skipped for unregistered jokers: {:?}",
            joker_skips.values().map(|v| v.len()).sum::<usize>(),
            joker_skips
        );
    }

    // The fixture's shape, asserted so a case cannot silently disappear.
    assert_eq!(score_total, 16, "score cases in the fixture");
    assert_eq!(held_total, 4, "held cases in the fixture");
    assert_eq!(glass_checked, 4, "glass cases checked");
    assert_eq!(pool_checked, 44, "shop_pool cases checked");
    assert_eq!(
        score_checked + score_pess_skipped + score_joker_skipped,
        score_total,
        "every score case is either checked or skipped"
    );
    assert_eq!(
        held_checked + held_joker_skipped,
        held_total,
        "every held case is either checked or skipped"
    );

    // The coverage gaps, asserted by number and reason. If these drop, the Rust
    // registry or the preview machinery grew and the fixture now reaches further;
    // that is the point of keeping them visible.
    assert_eq!(
        score_pess_skipped, 1,
        "score cases skipped: no pessimistic preview RNG in Rust yet"
    );
    // The registry now carries every joker, so no score or held case is skipped
    // for a missing spec, and the fixture reaches all of them.
    assert_eq!(
        score_joker_skipped, 0,
        "score cases skipped: jokers the Rust registry does not carry yet ({:?})",
        joker_skips
    );
    assert_eq!(
        held_joker_skipped, 0,
        "held cases skipped: jokers the Rust registry does not carry yet ({:?})",
        joker_skips
    );
    assert_eq!(score_checked, 15, "score cases the Rust side checked");
    assert_eq!(held_checked, 4, "held cases the Rust side checked");
}
