//! Replay the Python `state.state_dict` against the Rust observation layer.
//!
//! The fixture is generated by `tools/gen_state_fixture.py`. Each case records
//! a run's identity plus every leaf of the Python state dictionary as
//! `path<TAB>typed-value`, keys sorted: integers as `i:`, floats as
//! `f:<f64 bits>` and strings as `s:`. The Rust `state_dict` is flattened the
//! same way and compared leaf by leaf.
//!
//! The comparison covers every leaf the fixture holds -- it asserts the count
//! per case and the number of distinct top-level keys (42, the count
//! `state_dict` returns), so a comparison that silently covered three keys
//! cannot pass. The cases pin the fields the Rust run cannot yet reproduce (the
//! boss, the round's voucher and the ante tags are rolled in Python and not
//! translated) and then populate the joker, consumable, shop and pack rows so
//! the four renderers are compared with something in them, not just empty.

use jimbot_sim::cards::{wrap, Card, Edition, Enhancement, Rank, Seal, Suit};
use jimbot_sim::consumables::{ConsumableInstance, ConsumableRef, ConsumableSpec};
use jimbot_sim::game::{GameState, PackChoice, Phase};
use jimbot_sim::jokers::JokerRef;
use jimbot_sim::shop::{pack_from_key, voucher_by_key, Shop, ShopSlot};
use jimbot_sim::state::{flatten_state, state_dict, top_key, StateValue};

const FIXTURE: &str = include_str!("fixtures/state.txt");

/// `state_dict` returns exactly this many top-level keys. Asserted per case so a
/// key added on one side and not the other is a failure, not a smaller count.
const TOP_LEVEL_KEYS: usize = 42;

/// One `case` line: everything `state_dict` reads, pinned identically on both
/// sides.
struct Setup {
    seed: String,
    deck: String,
    stake: i32,
    ante: i32,
    round: i32,
    money: i32,
    chips: i64,
    blind_index: i32,
    phase: Phase,
    hands_left: i32,
    discards_left: i32,
    ante_boss: String,
    tag: String,
    idol_rank: Option<Rank>,
    idol_suit: Option<Suit>,
    ancient_suit: Option<Suit>,
    mail_rank: Option<Rank>,
    castle_suit: Option<Suit>,
    selection: Vec<usize>,
    hand: Vec<String>,
    jokers: Vec<String>,
    consumables: Vec<String>,
    shop: bool,
    shop_slots: Vec<String>,
    shop_packs: Vec<String>,
    shop_vouchers: Vec<String>,
    shop_rerolls: i32,
    shop_free_rerolls: i32,
    shop_free_reroll_cost: bool,
    pack_key: String,
    pack_options: Vec<String>,
    pack_picks_left: i32,
    vouchers: Vec<String>,
    hands_played: i32,
}

fn phase_of(name: &str) -> Phase {
    match name {
        "blind_select" => Phase::BlindSelect,
        "playing" => Phase::Playing,
        "round_eval" => Phase::RoundEval,
        "shop" => Phase::Shop,
        "pack" => Phase::Pack,
        "game_over" => Phase::GameOver,
        "won" => Phase::Won,
        other => panic!("unknown phase {:?}", other),
    }
}

fn enhancement_of(name: &str) -> Enhancement {
    match name {
        "none" => Enhancement::None,
        "bonus" => Enhancement::Bonus,
        "mult" => Enhancement::Mult,
        "wild" => Enhancement::Wild,
        "glass" => Enhancement::Glass,
        "steel" => Enhancement::Steel,
        "stone" => Enhancement::Stone,
        "gold" => Enhancement::Gold,
        "lucky" => Enhancement::Lucky,
        other => panic!("unknown enhancement {:?}", other),
    }
}

fn edition_of(name: &str) -> Edition {
    match name {
        "none" => Edition::None,
        "foil" => Edition::Foil,
        "holo" => Edition::Holographic,
        "polychrome" => Edition::Polychrome,
        "negative" => Edition::Negative,
        other => panic!("unknown edition {:?}", other),
    }
}

fn seal_of(name: &str) -> Seal {
    match name {
        "none" => Seal::None,
        "gold" => Seal::Gold,
        "red" => Seal::Red,
        "blue" => Seal::Blue,
        "purple" => Seal::Purple,
        other => panic!("unknown seal {:?}", other),
    }
}

fn rank_of(code: &str) -> Option<Rank> {
    if code == "-" {
        None
    } else {
        Some(Rank::from_code(code).unwrap_or_else(|| panic!("bad rank {:?}", code)))
    }
}

fn suit_of(code: &str) -> Option<Suit> {
    if code == "-" {
        None
    } else {
        Some(Suit::from_code(code).unwrap_or_else(|| panic!("bad suit {:?}", code)))
    }
}

/// `;`-separated list, empty string to no items.
fn split_list(text: &str) -> Vec<String> {
    if text.is_empty() {
        Vec::new()
    } else {
        text.split(';').map(|s| s.to_string()).collect()
    }
}

/// A joker, from the generator's `|`-separated fields.
///
/// A blank field keeps the joker's default, matching Python's `make(name)` with
/// that keyword omitted; a zero counter keeps the spec's `init_counter`, exactly
/// as Python's `JokerInstance.__post_init__` does.
fn build_joker(spec: &str) -> JokerRef {
    let fields: Vec<&str> = spec.split('|').collect();
    assert_eq!(fields.len(), 11, "joker spec {:?}", spec);
    let joker = jimbot_sim::jokers::make(fields[0]);
    {
        let mut j = joker.borrow_mut();
        if !fields[1].is_empty() {
            j.edition = edition_of(fields[1]);
        }
        if !fields[2].is_empty() {
            j.eternal = fields[2] == "1";
        }
        if !fields[3].is_empty() {
            j.perishable = fields[3] == "1";
        }
        if !fields[4].is_empty() {
            j.rental = fields[4] == "1";
        }
        if !fields[5].is_empty() {
            let counter: f64 = fields[5].parse().unwrap();
            if counter != 0.0 {
                j.counter = counter;
            }
        }
        if !fields[6].is_empty() {
            let secondary: f64 = fields[6].parse().unwrap();
            if secondary != 0.0 {
                j.secondary = secondary;
            }
        }
        if !fields[7].is_empty() {
            j.debuffed = fields[7] == "1";
        }
        if !fields[8].is_empty() {
            j.perish_tally = fields[8].parse().unwrap();
        }
        if !fields[9].is_empty() {
            j.hands_at_create = fields[9].parse().unwrap();
        }
        if !fields[10].is_empty() {
            j.extra_sell_value = fields[10].parse().unwrap();
        }
    }
    joker
}

/// A held consumable, from the generator's `name|edition|extra_sell_value`.
fn build_consumable(spec: &str) -> ConsumableRef {
    let fields: Vec<&str> = spec.split('|').collect();
    let edition = if fields.len() > 1 && !fields[1].is_empty() {
        edition_of(fields[1])
    } else {
        Edition::None
    };
    let spec = jimbot_sim::consumables::spec_or_panic(fields[0]);
    let mut held = ConsumableInstance::new(spec, edition);
    if fields.len() > 2 && !fields[2].is_empty() {
        held.extra_sell_value = fields[2].parse().unwrap();
    }
    jimbot_sim::consumables::make_ref(held)
}

fn consumable_spec(name: &str) -> &'static ConsumableSpec {
    jimbot_sim::consumables::spec_or_panic(name)
}

/// One shop slot, from the generator's ten `|`-separated fields.
fn build_shop_slot(spec: &str) -> ShopSlot {
    let f: Vec<&str> = spec.split('|').collect();
    assert_eq!(f.len(), 10, "shop slot spec {:?}", spec);
    // `kind` has to be static; the generator writes the same three words.
    let kind: &'static str = match f[0] {
        "joker" => "joker",
        "consumable" => "consumable",
        "card" => "card",
        other => panic!("unknown shop slot kind {:?}", other),
    };
    let mut slot = ShopSlot::new(kind, f[1].parse().unwrap());
    slot.couponed = f[2] == "1";
    if !f[3].is_empty() {
        let joker = build_joker(&format!(
            "{}|{}|{}|{}|{}|||0|0|0|0",
            f[3], f[4], f[5], f[6], f[7]
        ));
        slot.joker = Some(joker);
    }
    if !f[8].is_empty() {
        slot.consumable = Some(consumable_spec(f[8]));
    }
    if !f[9].is_empty() {
        slot.card = Some(wrap(make_card(f[9])));
    }
    slot
}

/// One pack option, from the generator's `J|...`, `C|...` or `K|...`.
fn build_pack_option(spec: &str) -> PackChoice {
    let (tag, rest) = spec
        .split_once('|')
        .unwrap_or_else(|| panic!("pack option spec {:?}", spec));
    match tag {
        "J" => PackChoice::Joker(build_joker(rest)),
        "C" => PackChoice::Card(wrap(make_card(rest))),
        "K" => PackChoice::Consumable(consumable_spec(rest)),
        other => panic!("unknown pack option kind {:?}", other),
    }
}

/// `rank:suit:enh:edn:seal:extra_chips:debuffed`, as the generator writes it.
fn make_card(spec: &str) -> Card {
    let parts: Vec<&str> = spec.split(':').collect();
    assert_eq!(parts.len(), 7, "card spec {:?}", spec);
    let rank = Rank::from_code(parts[0]).unwrap();
    let suit = Suit::from_code(parts[1]).unwrap();
    let mut card = Card::new(rank, suit);
    card.enhancement = enhancement_of(parts[2]);
    card.edition = edition_of(parts[3]);
    card.seal = seal_of(parts[4]);
    card.extra_chips = parts[5].parse().unwrap();
    card.debuffed = parts[6] == "1";
    card
}

fn parse_case(fields: &[&str]) -> Setup {
    assert_eq!(fields.len(), 34, "case fields: {:?}", fields);
    Setup {
        seed: fields[0].to_string(),
        deck: fields[1].to_string(),
        stake: fields[2].parse().unwrap(),
        ante: fields[3].parse().unwrap(),
        round: fields[4].parse().unwrap(),
        money: fields[5].parse().unwrap(),
        chips: fields[6].parse().unwrap(),
        blind_index: fields[7].parse().unwrap(),
        phase: phase_of(fields[8]),
        hands_left: fields[9].parse().unwrap(),
        discards_left: fields[10].parse().unwrap(),
        ante_boss: fields[11].to_string(),
        tag: fields[12].to_string(),
        idol_rank: rank_of(fields[13]),
        idol_suit: suit_of(fields[14]),
        ancient_suit: suit_of(fields[15]),
        mail_rank: rank_of(fields[16]),
        castle_suit: suit_of(fields[17]),
        selection: if fields[18].is_empty() {
            Vec::new()
        } else {
            fields[18].split(',').map(|i| i.parse().unwrap()).collect()
        },
        hand: split_list(fields[19]),
        jokers: split_list(fields[20]),
        consumables: split_list(fields[21]),
        shop: fields[22] == "1",
        shop_slots: split_list(fields[23]),
        shop_packs: split_list(fields[24]),
        shop_vouchers: split_list(fields[25]),
        shop_rerolls: fields[26].parse().unwrap(),
        shop_free_rerolls: fields[27].parse().unwrap(),
        shop_free_reroll_cost: fields[28] == "1",
        pack_key: fields[29].to_string(),
        pack_options: split_list(fields[30]),
        pack_picks_left: fields[31].parse().unwrap(),
        vouchers: split_list(fields[32]),
        hands_played: fields[33].parse().unwrap(),
    }
}

fn build_game(setup: &Setup) -> GameState {
    let mut game = GameState::new(setup.seed.as_str(), &setup.deck, setup.stake);
    game.blind = None;
    game.ante_boss = setup.ante_boss.clone();
    game.ante_tag_keys = if setup.tag.is_empty() {
        Vec::new()
    } else {
        vec![setup.tag.clone()]
    };
    game.ante = setup.ante;
    game.round_number = setup.round;
    game.money = setup.money;
    game.chips_scored = setup.chips;
    game.blind_index = setup.blind_index;
    game.phase = setup.phase;
    game.hands_left = setup.hands_left;
    game.discards_left = setup.discards_left;
    game.idol_rank = setup.idol_rank;
    game.idol_suit = setup.idol_suit;
    game.ancient_suit = setup.ancient_suit;
    game.mail_rank = setup.mail_rank;
    game.castle_suit = setup.castle_suit;
    game.hand = setup
        .hand
        .iter()
        .map(|spec| wrap(make_card(spec)))
        .collect();
    game.hands_played = setup.hands_played;
    game.jokers = setup.jokers.iter().map(|spec| build_joker(spec)).collect();
    game.consumables = setup
        .consumables
        .iter()
        .map(|spec| build_consumable(spec))
        .collect();
    game.vouchers = setup
        .vouchers
        .iter()
        .map(|key| voucher_by_key(key).unwrap_or_else(|| panic!("no voucher with key {:?}", key)))
        .collect();
    if setup.shop {
        let mut shop = Shop::default();
        shop.slots = setup
            .shop_slots
            .iter()
            .map(|spec| build_shop_slot(spec))
            .collect();
        shop.packs = setup
            .shop_packs
            .iter()
            .map(|key| pack_from_key(key))
            .collect();
        shop.vouchers = setup
            .shop_vouchers
            .iter()
            .map(|key| {
                voucher_by_key(key).unwrap_or_else(|| panic!("no voucher with key {:?}", key))
            })
            .collect();
        shop.rerolls = setup.shop_rerolls;
        shop.free_rerolls = setup.shop_free_rerolls;
        shop.free_reroll_cost = setup.shop_free_reroll_cost;
        game.shop = Some(shop);
    }
    if !setup.pack_key.is_empty() {
        game.pack = Some(pack_from_key(&setup.pack_key));
    }
    game.pack_options = setup
        .pack_options
        .iter()
        .map(|spec| build_pack_option(spec))
        .collect();
    game.pack_picks_left = setup.pack_picks_left;
    game
}

fn run_case(
    setup: &Setup,
    want: &[(String, String)],
    compared: &mut usize,
    fixture_top_keys: &mut std::collections::BTreeSet<String>,
) {
    for (path, _) in want {
        fixture_top_keys.insert(top_key(path).to_string());
    }

    let game = build_game(setup);
    let value = state_dict(&game, &setup.selection, 0, 0);

    // The comparison has to cover every key `state_dict` returns, not a floor:
    // a key that went missing on one side is exactly what this fixture exists
    // to catch, so the count is asserted rather than printed.
    match &value {
        StateValue::Map(m) => assert_eq!(
            m.len(),
            TOP_LEVEL_KEYS,
            "case {}: state_dict returned {} top-level keys, expected {}",
            setup.seed,
            m.len(),
            TOP_LEVEL_KEYS
        ),
        other => panic!("case {}: state_dict is not a map: {:?}", setup.seed, other),
    }

    let mut got = Vec::new();
    flatten_state(&value, "", &mut got);

    assert_eq!(
        got.len(),
        want.len(),
        "case {}: leaf count differs",
        setup.seed
    );
    for (index, (got_path, got_value)) in got.iter().enumerate() {
        let (want_path, want_value) = &want[index];
        assert_eq!(
            got_path, want_path,
            "case {}: leaf {} out of order",
            setup.seed, index
        );
        // The first differing path, named, so a failure says which key.
        assert_eq!(
            got_value, want_value,
            "case {}: first differing path {:?}",
            setup.seed, got_path
        );
    }
    *compared += got.len();
}

#[test]
fn state_fixture_matches_python() {
    let mut setup: Option<Setup> = None;
    let mut leaves: Vec<(String, String)> = Vec::new();
    let mut compared = 0usize;
    let mut cases = 0usize;
    let mut fixture_top_keys: std::collections::BTreeSet<String> =
        std::collections::BTreeSet::new();

    for line in FIXTURE.lines() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(rest) = line.strip_prefix("case\t") {
            if let Some(previous) = setup.take() {
                run_case(&previous, &leaves, &mut compared, &mut fixture_top_keys);
                cases += 1;
            }
            let fields: Vec<&str> = rest.split('\t').collect();
            setup = Some(parse_case(&fields));
            leaves = Vec::new();
        } else {
            let (path, value) = line
                .split_once('\t')
                .unwrap_or_else(|| panic!("malformed fixture line {:?}", line));
            leaves.push((path.to_string(), value.to_string()));
        }
    }
    if let Some(previous) = setup {
        run_case(&previous, &leaves, &mut compared, &mut fixture_top_keys);
        cases += 1;
    }

    // The covered-key count is the point: reporting it is what stops a
    // comparison that quietly covers almost nothing from passing. The fixture's
    // own top-level keys must be exactly the count `state_dict` returns, so a
    // key that only one engine builds fails here even if every other leaf
    // matches.
    println!(
        "state fixture: {} cases, {} leaves compared, {} top-level keys",
        cases,
        compared,
        fixture_top_keys.len()
    );
    assert!(cases >= 6, "only {} cases compared", cases);
    assert_eq!(
        fixture_top_keys.len(),
        TOP_LEVEL_KEYS,
        "fixture covered top-level keys {:?}",
        fixture_top_keys
    );
    assert!(
        compared >= 1800,
        "fixture comparison covered only {} keys",
        compared
    );
}

/// Credit Card's whole mechanic, at the exact numbers `game.py` documents.
///
/// `game.py:1549`'s `affords` docstring is the specification: every
/// affordability test is `cost <= dollars - bankrupt_at` (with a free-item
/// escape), Credit Card moves `bankrupt_at` by -20, and they stack. No
/// recording ever held one, so this pins the numbers by hand: at $0 one card
/// allows $20 and refuses $21; two allow $40 and refuse $41; `affords(0)` is
/// true even past the floor. A `bankrupt_at`/`spendable`/`affords` that is off
/// by one, or that ignores Credit Card, fails here.
#[test]
fn credit_card_affordability_matches_the_game() {
    const CARD: &str = "Credit Card|none|0|0|0|0|0|0|0|0|0";

    // No Credit Card: the floor is zero, so nothing at all is affordable.
    let mut game = GameState::new("CREDITCARD", "Red Deck", 1);
    game.money = 0;
    assert_eq!(game.bankrupt_at(), 0);
    assert_eq!(game.spendable(), 0);
    assert!(!game.affords(1));

    // One Credit Card at $0: a $20 buy is allowed, $21 is refused.
    game.jokers = vec![build_joker(CARD)];
    assert_eq!(game.bankrupt_at(), -20);
    assert_eq!(game.spendable(), 20);
    assert!(game.affords(20));
    assert!(!game.affords(21));

    // Two stack: $40 allowed, $41 refused.
    game.jokers.push(build_joker(CARD));
    assert_eq!(game.bankrupt_at(), -40);
    assert_eq!(game.spendable(), 40);
    assert!(game.affords(40));
    assert!(!game.affords(41));

    // The free-item escape: `affords(0)` is true even with `spendable`
    // negative. Two cards put the floor at -40, so $ -50 is $10 past it.
    game.money = -50;
    assert_eq!(game.spendable(), -10);
    assert!(game.affords(0));
    assert!(!game.affords(1));
}

/// A won run: `won` is 1 and `state_name` is `GAME_OVER` (both matter).
///
/// `state.py:73` maps the `won` phase to `GAME_OVER`; the fixture case proves
/// the leaf comparison, this proves the pair directly.
#[test]
fn won_phase_is_won_and_game_over() {
    let mut game = GameState::new("WONPHASE", "Red Deck", 1);
    game.phase = Phase::Won;
    let mut leaves = Vec::new();
    flatten_state(&state_dict(&game, &[], 0, 0), "", &mut leaves);
    let got: std::collections::HashMap<String, String> = leaves.into_iter().collect();
    assert_eq!(got["won"], "i:1");
    assert_eq!(got["state_name"], "s:GAME_OVER");
}
