//! Boss blinds and how the game picks one.
//!
//! Generated by ops/gen_boss_data.py. Do not edit by hand.
//!
//! `min` is the earliest ante a boss can appear at. `showdown` marks the finisher
//! bosses, which appear only on the ante that ends a run and never before ante 2.
//! `mult` is the blind's chip multiplier.
//!
//! The order here is alphabetical by key on purpose: the game draws with
//! pseudorandom_element over a keyed table, which sorts the keys before picking,
//! so alphabetical order is part of the distribution.

use std::collections::HashMap;

/// One row of the game's own P_BLINDS-derived table: `key -> (name, min_ante,
/// showdown, chip_mult)`.
#[derive(Clone, Copy, Debug)]
pub struct BossRow {
    pub key: &'static str,
    pub name: &'static str,
    pub min_ante: i32,
    pub showdown: bool,
    pub chip_mult: f64,
}

/// key -> (name, min_ante, showdown, chip_mult), alphabetical by key.
pub const BOSS_DATA: &[BossRow] = &[
    BossRow { key: "bl_arm", name: "The Arm", min_ante: 2, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_club", name: "The Club", min_ante: 1, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_eye", name: "The Eye", min_ante: 3, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_final_acorn", name: "Amber Acorn", min_ante: 10, showdown: true, chip_mult: 2.0 },
    BossRow { key: "bl_final_bell", name: "Cerulean Bell", min_ante: 10, showdown: true, chip_mult: 2.0 },
    BossRow { key: "bl_final_heart", name: "Crimson Heart", min_ante: 10, showdown: true, chip_mult: 2.0 },
    BossRow { key: "bl_final_leaf", name: "Verdant Leaf", min_ante: 10, showdown: true, chip_mult: 2.0 },
    BossRow { key: "bl_final_vessel", name: "Violet Vessel", min_ante: 10, showdown: true, chip_mult: 6.0 },
    BossRow { key: "bl_fish", name: "The Fish", min_ante: 2, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_flint", name: "The Flint", min_ante: 2, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_goad", name: "The Goad", min_ante: 1, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_head", name: "The Head", min_ante: 1, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_hook", name: "The Hook", min_ante: 1, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_house", name: "The House", min_ante: 2, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_manacle", name: "The Manacle", min_ante: 1, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_mark", name: "The Mark", min_ante: 2, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_mouth", name: "The Mouth", min_ante: 2, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_needle", name: "The Needle", min_ante: 2, showdown: false, chip_mult: 1.0 },
    BossRow { key: "bl_ox", name: "The Ox", min_ante: 6, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_pillar", name: "The Pillar", min_ante: 1, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_plant", name: "The Plant", min_ante: 4, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_psychic", name: "The Psychic", min_ante: 1, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_serpent", name: "The Serpent", min_ante: 5, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_tooth", name: "The Tooth", min_ante: 3, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_wall", name: "The Wall", min_ante: 2, showdown: false, chip_mult: 4.0 },
    BossRow { key: "bl_water", name: "The Water", min_ante: 2, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_wheel", name: "The Wheel", min_ante: 2, showdown: false, chip_mult: 2.0 },
    BossRow { key: "bl_window", name: "The Window", min_ante: 1, showdown: false, chip_mult: 2.0 },
];

/// The row for a boss key, or `None` if the key is unknown.
pub fn boss_row(key: &str) -> Option<&'static BossRow> {
    BOSS_DATA.iter().find(|row| row.key == key)
}

/// Boss keys the game would consider for this ante, least-used only.
///
/// Two filters, and the second is the one that is easy to miss. Showdown
/// bosses appear only on the ante that ends a run; ordinary ones only when it
/// does not. Then the set is narrowed to those used fewest so far, which is
/// why a run does not see the same boss twice while others are unplayed --
/// a uniform draw over all eligible bosses is a different game.
pub fn eligible_bosses(ante: i32, used: &HashMap<String, i32>, win_ante: i32) -> Vec<&'static str> {
    let ante = ante.max(1);
    let finisher = ante % win_ante == 0 && ante >= 2;
    let mut pool: Vec<&'static str> = Vec::new();
    for row in BOSS_DATA {
        if row.showdown {
            if finisher {
                pool.push(row.key);
            }
        } else if row.min_ante <= ante && !finisher {
            pool.push(row.key);
        }
    }

    if pool.is_empty() {
        return Vec::new();
    }
    let fewest = pool.iter().map(|key| *used.get(*key).unwrap_or(&0)).min().unwrap();
    // Keys sorted, because pseudorandom_element sorts a keyed table before it
    // picks and the order therefore decides which key an index lands on.
    let mut out: Vec<&'static str> = pool
        .into_iter()
        .filter(|key| *used.get(*key).unwrap_or(&0) == fewest)
        .collect();
    out.sort_unstable();
    out
}
