//! Generated by tools/gen_consumable_data_rs.py from jimbot_sim.consumable_data; do not edit by hand.
//!
//! Consumable identity and shop pool order, taken from the game.
//!
//! Generated by ops/gen_consumable_data.py. Do not edit by hand.
//!
//! Two rules live in this data rather than in code:
//!
//!   softlock   a Planet card for a hand nobody has played is not in the pool.
//!              Planet X, Ceres and Eris are the ones that matter, since Five of
//!              a Kind, Flush House and Flush Five need a deck built for them.
//!   excluded   Black Hole and The Soul never come from an ordinary draw.

#[derive(Clone, Copy, Debug)]
pub struct ConsumableRow {
    /// "Tarot" | "Planet" | "Spectral".
    pub set: &'static str,
    pub key: &'static str,
    pub name: &'static str,
    pub order: i32,
    pub softlock: bool,
    /// The hand type a Planet levels, or "" for Tarots/Spectrals.
    pub hand_type: &'static str,
}

/// Every consumable: Tarot, then Planet, then Spectral, each in
/// the game's pool order (the order the shop draws by index).
pub const CONSUMABLE_DATA: &[ConsumableRow] = &[
    ConsumableRow { set: "Tarot", key: "c_fool", name: "The Fool", order: 1, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_magician", name: "The Magician", order: 2, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_high_priestess", name: "The High Priestess", order: 3, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_empress", name: "The Empress", order: 4, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_emperor", name: "The Emperor", order: 5, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_heirophant", name: "The Hierophant", order: 6, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_lovers", name: "The Lovers", order: 7, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_chariot", name: "The Chariot", order: 8, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_justice", name: "Justice", order: 9, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_hermit", name: "The Hermit", order: 10, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_wheel_of_fortune", name: "The Wheel of Fortune", order: 11, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_strength", name: "Strength", order: 12, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_hanged_man", name: "The Hanged Man", order: 13, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_death", name: "Death", order: 14, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_temperance", name: "Temperance", order: 15, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_devil", name: "The Devil", order: 16, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_tower", name: "The Tower", order: 17, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_star", name: "The Star", order: 18, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_moon", name: "The Moon", order: 19, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_sun", name: "The Sun", order: 20, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_judgement", name: "Judgement", order: 21, softlock: false, hand_type: "" },
    ConsumableRow { set: "Tarot", key: "c_world", name: "The World", order: 22, softlock: false, hand_type: "" },
    ConsumableRow { set: "Planet", key: "c_mercury", name: "Mercury", order: 1, softlock: false, hand_type: "Pair" },
    ConsumableRow { set: "Planet", key: "c_venus", name: "Venus", order: 2, softlock: false, hand_type: "Three of a Kind" },
    ConsumableRow { set: "Planet", key: "c_earth", name: "Earth", order: 3, softlock: false, hand_type: "Full House" },
    ConsumableRow { set: "Planet", key: "c_mars", name: "Mars", order: 4, softlock: false, hand_type: "Four of a Kind" },
    ConsumableRow { set: "Planet", key: "c_jupiter", name: "Jupiter", order: 5, softlock: false, hand_type: "Flush" },
    ConsumableRow { set: "Planet", key: "c_saturn", name: "Saturn", order: 6, softlock: false, hand_type: "Straight" },
    ConsumableRow { set: "Planet", key: "c_uranus", name: "Uranus", order: 7, softlock: false, hand_type: "Two Pair" },
    ConsumableRow { set: "Planet", key: "c_neptune", name: "Neptune", order: 8, softlock: false, hand_type: "Straight Flush" },
    ConsumableRow { set: "Planet", key: "c_pluto", name: "Pluto", order: 9, softlock: false, hand_type: "High Card" },
    ConsumableRow { set: "Planet", key: "c_planet_x", name: "Planet X", order: 10, softlock: true, hand_type: "Five of a Kind" },
    ConsumableRow { set: "Planet", key: "c_ceres", name: "Ceres", order: 11, softlock: true, hand_type: "Flush House" },
    ConsumableRow { set: "Planet", key: "c_eris", name: "Eris", order: 12, softlock: true, hand_type: "Flush Five" },
    ConsumableRow { set: "Spectral", key: "c_familiar", name: "Familiar", order: 1, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_grim", name: "Grim", order: 2, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_incantation", name: "Incantation", order: 3, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_talisman", name: "Talisman", order: 4, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_aura", name: "Aura", order: 5, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_wraith", name: "Wraith", order: 6, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_sigil", name: "Sigil", order: 7, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_ouija", name: "Ouija", order: 8, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_ectoplasm", name: "Ectoplasm", order: 9, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_immolate", name: "Immolate", order: 10, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_ankh", name: "Ankh", order: 11, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_deja_vu", name: "Deja Vu", order: 12, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_hex", name: "Hex", order: 13, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_trance", name: "Trance", order: 14, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_medium", name: "Medium", order: 15, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_cryptid", name: "Cryptid", order: 16, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_soul", name: "The Soul", order: 17, softlock: false, hand_type: "" },
    ConsumableRow { set: "Spectral", key: "c_black_hole", name: "Black Hole", order: 18, softlock: false, hand_type: "" },
];

/// Never drawn from an ordinary pool; they have their own path.
pub const EXCLUDED_FROM_POOLS: [&'static str; 2] = ["Black Hole", "The Soul"];

/// Look up a consumable by its display name.
///
/// Linear over 52 rows; a map would cost more to build than the
/// handful of lookups a run makes.
pub fn consumable_row(name: &str) -> Option<&'static ConsumableRow> {
    CONSUMABLE_DATA.iter().find(|row| row.name == name)
}

/// Look up a consumable by its internal key (e.g. `c_fool`).
pub fn consumable_row_by_key(key: &str) -> Option<&'static ConsumableRow> {
    CONSUMABLE_DATA.iter().find(|row| row.key == key)
}

/// All consumables of a set, in pool order.
pub fn consumable_rows_for_set(set: &str) -> Vec<&'static ConsumableRow> {
    CONSUMABLE_DATA.iter().filter(|row| row.set == set).collect()
}
