//! Deck (back) effects, taken from the game.
//!
//! Generated by ops/gen_deck_data.py. Do not edit by hand.
//!
//! Each entry is the back's own config table. The names are the game's, so
//! `discards` means "extra discards each round" and `dollars` means "extra
//! starting money" -- a deck contributes these on top of the base rules rather
//! than replacing them.

/// A deck back's own config table, with every field the game reads a default
/// for.
///
/// The game writes only the keys a deck actually sets and reads the rest with
/// `.get(key, default)`. [`DeckConfig::empty`] and [`Default`] hold those same
/// defaults -- in particular `extra_hand_bonus` is 1 (the usual dollar per
/// unspent hand) and `ante_scaling` is 1, so a row that does not name a field
/// behaves exactly as the Python `.get` did.
#[derive(Clone, Copy, Debug)]
pub struct DeckConfig {
    pub key: &'static str,
    pub remove_faces: bool,
    pub double_tag_after_boss: bool,
    pub hands: i32,
    pub joker_slot: i32,
    pub discards: i32,
    pub dollars: i32,
    pub hand_size: i32,
    pub ante_scaling: f64,
    pub consumable_slot: i32,
    pub randomize_rank_suit: bool,
    pub extra_hand_bonus: i32,
    pub extra_discard_bonus: i32,
    pub no_interest: bool,
    pub spectral_rate: i32,
    pub consumables: &'static [&'static str],
    pub voucher: &'static str,
    pub vouchers: &'static [&'static str],
}

impl DeckConfig {
    /// The config an unknown deck gets, and the base every row starts from.
    ///
    /// These are the defaults Python reads with `config.get(key, default)`:
    /// `ante_scaling` 1, `hand_size` 0, `extra_hand_bonus` 1,
    /// `extra_discard_bonus` 0, `spectral_rate` 0 and so on.
    pub const fn empty() -> DeckConfig {
        DeckConfig {
            key: "",
            remove_faces: false,
            double_tag_after_boss: false,
            hands: 0,
            joker_slot: 0,
            discards: 0,
            dollars: 0,
            hand_size: 0,
            ante_scaling: 1.0,
            consumable_slot: 0,
            randomize_rank_suit: false,
            extra_hand_bonus: 1,
            extra_discard_bonus: 0,
            no_interest: false,
            spectral_rate: 0,
            consumables: &[],
            voucher: "",
            vouchers: &[],
        }
    }

    /// The empty config, always available, for `deck_config`'s unknown case.
    pub const EMPTY: DeckConfig = DeckConfig::empty();
}

impl Default for DeckConfig {
    fn default() -> Self {
        DeckConfig::empty()
    }
}

/// display name -> (key, config), in the Python dict's order.
pub const DECK_DATA: &[(&str, DeckConfig)] = &[
    (
        "Abandoned Deck",
        DeckConfig {
            key: "b_abandoned",
            remove_faces: true,
            ..DeckConfig::empty()
        },
    ),
    (
        "Anaglyph Deck",
        DeckConfig {
            key: "b_anaglyph",
            double_tag_after_boss: true,
            ..DeckConfig::empty()
        },
    ),
    (
        "Black Deck",
        DeckConfig {
            key: "b_black",
            hands: -1,
            joker_slot: 1,
            ..DeckConfig::empty()
        },
    ),
    (
        "Blue Deck",
        DeckConfig {
            key: "b_blue",
            hands: 1,
            ..DeckConfig::empty()
        },
    ),
    (
        "Challenge Deck",
        DeckConfig {
            key: "b_challenge",
            ..DeckConfig::empty()
        },
    ),
    (
        "Checkered Deck",
        DeckConfig {
            key: "b_checkered",
            ..DeckConfig::empty()
        },
    ),
    (
        "Erratic Deck",
        DeckConfig {
            key: "b_erratic",
            randomize_rank_suit: true,
            ..DeckConfig::empty()
        },
    ),
    (
        "Ghost Deck",
        DeckConfig {
            key: "b_ghost",
            spectral_rate: 2,
            consumables: &["c_hex"],
            ..DeckConfig::empty()
        },
    ),
    (
        "Green Deck",
        DeckConfig {
            key: "b_green",
            extra_hand_bonus: 2,
            extra_discard_bonus: 1,
            no_interest: true,
            ..DeckConfig::empty()
        },
    ),
    (
        "Magic Deck",
        DeckConfig {
            key: "b_magic",
            consumables: &["c_fool", "c_fool"],
            voucher: "v_crystal_ball",
            ..DeckConfig::empty()
        },
    ),
    (
        "Nebula Deck",
        DeckConfig {
            key: "b_nebula",
            consumable_slot: -1,
            voucher: "v_telescope",
            ..DeckConfig::empty()
        },
    ),
    (
        "Painted Deck",
        DeckConfig {
            key: "b_painted",
            hand_size: 2,
            joker_slot: -1,
            ..DeckConfig::empty()
        },
    ),
    (
        "Plasma Deck",
        DeckConfig {
            key: "b_plasma",
            ante_scaling: 2.0,
            ..DeckConfig::empty()
        },
    ),
    (
        "Red Deck",
        DeckConfig {
            key: "b_red",
            discards: 1,
            ..DeckConfig::empty()
        },
    ),
    (
        "Yellow Deck",
        DeckConfig {
            key: "b_yellow",
            dollars: 10,
            ..DeckConfig::empty()
        },
    ),
    (
        "Zodiac Deck",
        DeckConfig {
            key: "b_zodiac",
            vouchers: &["v_tarot_merchant", "v_planet_merchant", "v_overstock_norm"],
            ..DeckConfig::empty()
        },
    ),
];

/// The config for a deck name, or the empty one for an unknown name.
///
/// Python: `DECK_DATA.get(deck, ("", {}))[1]`.
pub fn deck_config(deck: &str) -> &'static DeckConfig {
    DECK_DATA
        .iter()
        .find(|(name, _)| *name == deck)
        .map(|(_, config)| config)
        .unwrap_or(&DeckConfig::EMPTY)
}
