//! Generated by tools/gen_joker_data_rs.py from jimbot_sim.joker_data; do not edit by hand.
//!
//! Joker identity and shop pool order, taken from the game.
//!
//! The shop picks a joker by drawing an index into the pool for a rarity, so this
//! order is part of the distribution rather than a display detail: a pool in a
//! different order offers different jokers at different rates from the same seed,
//! while every rule still looks right.
//!
//! Generated by ops/gen_joker_data.py against the real centers. Do not edit by
//! hand -- regenerate it.

#[derive(Clone, Copy, Debug)]
pub struct JokerRow {
    pub name: &'static str,
    pub key: &'static str,
    pub rarity: u8,
    pub order: i32,
    pub unlocked: bool,
    pub enhancement_gate: &'static str,
    pub no_flag: &'static str,
    pub yes_flag: &'static str,
    pub eternal_ok: bool,
    pub perishable_ok: bool,
}

/// Every joker, in the Python dict's insertion order. The
/// insertion order is what `pool_for_rarity` sorts by `order`.
pub const JOKER_DATA: &[JokerRow] = &[
    JokerRow { name: "Joker", key: "j_joker", rarity: 1, order: 1, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Greedy Joker", key: "j_greedy_joker", rarity: 1, order: 2, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Lusty Joker", key: "j_lusty_joker", rarity: 1, order: 3, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Wrathful Joker", key: "j_wrathful_joker", rarity: 1, order: 4, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Gluttonous Joker", key: "j_gluttenous_joker", rarity: 1, order: 5, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Jolly Joker", key: "j_jolly", rarity: 1, order: 6, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Zany Joker", key: "j_zany", rarity: 1, order: 7, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Mad Joker", key: "j_mad", rarity: 1, order: 8, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Crazy Joker", key: "j_crazy", rarity: 1, order: 9, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Droll Joker", key: "j_droll", rarity: 1, order: 10, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Sly Joker", key: "j_sly", rarity: 1, order: 11, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Wily Joker", key: "j_wily", rarity: 1, order: 12, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Clever Joker", key: "j_clever", rarity: 1, order: 13, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Devious Joker", key: "j_devious", rarity: 1, order: 14, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Crafty Joker", key: "j_crafty", rarity: 1, order: 15, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Half Joker", key: "j_half", rarity: 1, order: 16, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Credit Card", key: "j_credit_card", rarity: 1, order: 20, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Banner", key: "j_banner", rarity: 1, order: 22, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Mystic Summit", key: "j_mystic_summit", rarity: 1, order: 23, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "8 Ball", key: "j_8_ball", rarity: 1, order: 26, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Misprint", key: "j_misprint", rarity: 1, order: 27, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Raised Fist", key: "j_raised_fist", rarity: 1, order: 29, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Chaos the Clown", key: "j_chaos", rarity: 1, order: 30, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Scary Face", key: "j_scary_face", rarity: 1, order: 33, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Abstract Joker", key: "j_abstract", rarity: 1, order: 34, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Delayed Gratification", key: "j_delayed_grat", rarity: 1, order: 35, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Gros Michel", key: "j_gros_michel", rarity: 1, order: 38, unlocked: true, enhancement_gate: "", no_flag: "gros_michel_extinct", yes_flag: "", eternal_ok: false, perishable_ok: true },
    JokerRow { name: "Even Steven", key: "j_even_steven", rarity: 1, order: 39, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Odd Todd", key: "j_odd_todd", rarity: 1, order: 40, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Scholar", key: "j_scholar", rarity: 1, order: 41, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Business Card", key: "j_business", rarity: 1, order: 42, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Supernova", key: "j_supernova", rarity: 1, order: 43, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Ride the Bus", key: "j_ride_the_bus", rarity: 1, order: 44, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Egg", key: "j_egg", rarity: 1, order: 46, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Runner", key: "j_runner", rarity: 1, order: 49, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Ice Cream", key: "j_ice_cream", rarity: 1, order: 50, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: false, perishable_ok: true },
    JokerRow { name: "Splash", key: "j_splash", rarity: 1, order: 52, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Blue Joker", key: "j_blue_joker", rarity: 1, order: 53, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Faceless Joker", key: "j_faceless", rarity: 1, order: 57, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Green Joker", key: "j_green_joker", rarity: 1, order: 58, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Superposition", key: "j_superposition", rarity: 1, order: 59, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "To Do List", key: "j_todo_list", rarity: 1, order: 60, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Cavendish", key: "j_cavendish", rarity: 1, order: 61, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "gros_michel_extinct", eternal_ok: false, perishable_ok: true },
    JokerRow { name: "Red Card", key: "j_red_card", rarity: 1, order: 63, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Square Joker", key: "j_square", rarity: 1, order: 65, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Riff-Raff", key: "j_riff_raff", rarity: 1, order: 67, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Photograph", key: "j_photograph", rarity: 1, order: 78, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Reserved Parking", key: "j_reserved_parking", rarity: 1, order: 82, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Mail-In Rebate", key: "j_mail", rarity: 1, order: 83, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Hallucination", key: "j_hallucination", rarity: 1, order: 85, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Fortune Teller", key: "j_fortune_teller", rarity: 1, order: 86, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Juggler", key: "j_juggler", rarity: 1, order: 87, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Drunkard", key: "j_drunkard", rarity: 1, order: 88, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Golden Joker", key: "j_golden", rarity: 1, order: 90, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Popcorn", key: "j_popcorn", rarity: 1, order: 97, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: false, perishable_ok: true },
    JokerRow { name: "Walkie Talkie", key: "j_walkie_talkie", rarity: 1, order: 101, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Smiley Face", key: "j_smiley", rarity: 1, order: 104, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Golden Ticket", key: "j_ticket", rarity: 1, order: 106, unlocked: true, enhancement_gate: "m_gold", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Swashbuckler", key: "j_swashbuckler", rarity: 1, order: 110, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Hanging Chad", key: "j_hanging_chad", rarity: 1, order: 115, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Shoot the Moon", key: "j_shoot_the_moon", rarity: 1, order: 140, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Joker Stencil", key: "j_stencil", rarity: 2, order: 17, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Four Fingers", key: "j_four_fingers", rarity: 2, order: 18, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Mime", key: "j_mime", rarity: 2, order: 19, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Ceremonial Dagger", key: "j_ceremonial", rarity: 2, order: 21, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Marble Joker", key: "j_marble", rarity: 2, order: 24, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Loyalty Card", key: "j_loyalty_card", rarity: 2, order: 25, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Dusk", key: "j_dusk", rarity: 2, order: 28, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Fibonacci", key: "j_fibonacci", rarity: 2, order: 31, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Steel Joker", key: "j_steel_joker", rarity: 2, order: 32, unlocked: true, enhancement_gate: "m_steel", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Hack", key: "j_hack", rarity: 2, order: 36, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Pareidolia", key: "j_pareidolia", rarity: 2, order: 37, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Space Joker", key: "j_space", rarity: 2, order: 45, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Burglar", key: "j_burglar", rarity: 2, order: 47, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Blackboard", key: "j_blackboard", rarity: 2, order: 48, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Sixth Sense", key: "j_sixth_sense", rarity: 2, order: 54, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Constellation", key: "j_constellation", rarity: 2, order: 55, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Hiker", key: "j_hiker", rarity: 2, order: 56, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Card Sharp", key: "j_card_sharp", rarity: 2, order: 62, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Madness", key: "j_madness", rarity: 2, order: 64, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Séance", key: "j_seance", rarity: 2, order: 66, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Vampire", key: "j_vampire", rarity: 2, order: 68, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Shortcut", key: "j_shortcut", rarity: 2, order: 69, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Hologram", key: "j_hologram", rarity: 2, order: 70, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Cloud 9", key: "j_cloud_9", rarity: 2, order: 73, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Rocket", key: "j_rocket", rarity: 2, order: 74, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Midas Mask", key: "j_midas_mask", rarity: 2, order: 76, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Luchador", key: "j_luchador", rarity: 2, order: 77, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: false, perishable_ok: true },
    JokerRow { name: "Gift Card", key: "j_gift", rarity: 2, order: 79, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Turtle Bean", key: "j_turtle_bean", rarity: 2, order: 80, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: false, perishable_ok: true },
    JokerRow { name: "Erosion", key: "j_erosion", rarity: 2, order: 81, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "To the Moon", key: "j_to_the_moon", rarity: 2, order: 84, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Stone Joker", key: "j_stone", rarity: 2, order: 89, unlocked: true, enhancement_gate: "m_stone", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Lucky Cat", key: "j_lucky_cat", rarity: 2, order: 91, unlocked: true, enhancement_gate: "m_lucky", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Bull", key: "j_bull", rarity: 2, order: 93, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Diet Cola", key: "j_diet_cola", rarity: 2, order: 94, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: false, perishable_ok: true },
    JokerRow { name: "Trading Card", key: "j_trading", rarity: 2, order: 95, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Flash Card", key: "j_flash", rarity: 2, order: 96, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Spare Trousers", key: "j_trousers", rarity: 2, order: 98, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Ramen", key: "j_ramen", rarity: 2, order: 100, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: false, perishable_ok: true },
    JokerRow { name: "Seltzer", key: "j_selzer", rarity: 2, order: 102, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: false, perishable_ok: true },
    JokerRow { name: "Castle", key: "j_castle", rarity: 2, order: 103, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Mr. Bones", key: "j_mr_bones", rarity: 2, order: 107, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: false, perishable_ok: true },
    JokerRow { name: "Acrobat", key: "j_acrobat", rarity: 2, order: 108, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Sock and Buskin", key: "j_sock_and_buskin", rarity: 2, order: 109, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Troubadour", key: "j_troubadour", rarity: 2, order: 111, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Certificate", key: "j_certificate", rarity: 2, order: 112, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Smeared Joker", key: "j_smeared", rarity: 2, order: 113, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Throwback", key: "j_throwback", rarity: 2, order: 114, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Rough Gem", key: "j_rough_gem", rarity: 2, order: 116, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Bloodstone", key: "j_bloodstone", rarity: 2, order: 117, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Arrowhead", key: "j_arrowhead", rarity: 2, order: 118, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Onyx Agate", key: "j_onyx_agate", rarity: 2, order: 119, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Glass Joker", key: "j_glass", rarity: 2, order: 120, unlocked: true, enhancement_gate: "m_glass", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Showman", key: "j_ring_master", rarity: 2, order: 121, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Flower Pot", key: "j_flower_pot", rarity: 2, order: 122, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Merry Andy", key: "j_merry_andy", rarity: 2, order: 125, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Oops! All 6s", key: "j_oops", rarity: 2, order: 126, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "The Idol", key: "j_idol", rarity: 2, order: 127, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Seeing Double", key: "j_seeing_double", rarity: 2, order: 128, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Matador", key: "j_matador", rarity: 2, order: 129, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Satellite", key: "j_satellite", rarity: 2, order: 139, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Cartomancer", key: "j_cartomancer", rarity: 2, order: 142, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Astronomer", key: "j_astronomer", rarity: 2, order: 143, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Bootstraps", key: "j_bootstraps", rarity: 2, order: 145, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "DNA", key: "j_dna", rarity: 3, order: 51, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Vagabond", key: "j_vagabond", rarity: 3, order: 71, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Baron", key: "j_baron", rarity: 3, order: 72, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Obelisk", key: "j_obelisk", rarity: 3, order: 75, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Baseball Card", key: "j_baseball", rarity: 3, order: 92, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Ancient Joker", key: "j_ancient", rarity: 3, order: 99, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Campfire", key: "j_campfire", rarity: 3, order: 105, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Blueprint", key: "j_blueprint", rarity: 3, order: 123, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Wee Joker", key: "j_wee", rarity: 3, order: 124, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: false },
    JokerRow { name: "Hit the Road", key: "j_hit_the_road", rarity: 3, order: 130, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "The Duo", key: "j_duo", rarity: 3, order: 131, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "The Trio", key: "j_trio", rarity: 3, order: 132, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "The Family", key: "j_family", rarity: 3, order: 133, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "The Order", key: "j_order", rarity: 3, order: 134, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "The Tribe", key: "j_tribe", rarity: 3, order: 135, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Stuntman", key: "j_stuntman", rarity: 3, order: 136, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Invisible Joker", key: "j_invisible", rarity: 3, order: 137, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: false, perishable_ok: true },
    JokerRow { name: "Brainstorm", key: "j_brainstorm", rarity: 3, order: 138, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Driver's License", key: "j_drivers_license", rarity: 3, order: 141, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Burnt Joker", key: "j_burnt", rarity: 3, order: 144, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Canio", key: "j_caino", rarity: 4, order: 146, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Triboulet", key: "j_triboulet", rarity: 4, order: 147, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Yorick", key: "j_yorick", rarity: 4, order: 148, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Chicot", key: "j_chicot", rarity: 4, order: 149, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
    JokerRow { name: "Perkeo", key: "j_perkeo", rarity: 4, order: 150, unlocked: true, enhancement_gate: "", no_flag: "", yes_flag: "", eternal_ok: true, perishable_ok: true },
];

/// Look up a joker by its display name.
///
/// Linear over 150 rows; a map would cost more to build than the
/// handful of lookups a run makes.
pub fn joker_row(name: &str) -> Option<&'static JokerRow> {
    JOKER_DATA.iter().find(|row| row.name == name)
}

/// Look up a joker by its internal key (e.g. `j_joker`).
pub fn joker_row_by_key(key: &str) -> Option<&'static JokerRow> {
    JOKER_DATA.iter().find(|row| row.key == key)
}

/// Joker rows of that rarity, in the game's pool order.
///
/// The shop draws an index into this list, so the sort is part of
/// the distribution, not a display detail.
pub fn pool_for_rarity(rarity: u8) -> Vec<&'static JokerRow> {
    let mut pool: Vec<&'static JokerRow> = JOKER_DATA
        .iter()
        .filter(|row| row.rarity == rarity)
        .collect();
    pool.sort_by_key(|row| row.order);
    pool
}

/// `pool_for_rarity` reduced to the keys the shop indexes by.
pub fn pool_for_rarity_keys(rarity: u8) -> Vec<&'static str> {
    pool_for_rarity(rarity).iter().map(|row| row.key).collect()
}
