//! Booster packs and their weights, taken from the game.
//!
//! Generated by ops/gen_pack_data.py. Do not edit by hand.
//!
//! `choose` is how many cards may be taken, `cards` how many are offered. The
//! order is the game's pool order and is load-bearing: the draw accumulates
//! weight along the list and takes the entry whose band contains the roll, so a
//! reordered list hands out different packs from the same seed.

/// One `(key, kind, weight, choose, cards, cost)` row, in the game's pool order.
#[derive(Clone, Copy, Debug)]
pub struct PackRow {
    pub key: &'static str,
    pub kind: &'static str,
    pub weight: f64,
    pub choose: i32,
    pub cards: i32,
    pub cost: i32,
}

/// (key, kind, weight, choose, cards, cost), in the game's pool order.
pub const PACK_DATA: &[PackRow] = &[
    PackRow { key: "p_arcana_normal_1", kind: "Arcana", weight: 1.0, choose: 1, cards: 3, cost: 4 },
    PackRow { key: "p_arcana_normal_2", kind: "Arcana", weight: 1.0, choose: 1, cards: 3, cost: 4 },
    PackRow { key: "p_arcana_normal_3", kind: "Arcana", weight: 1.0, choose: 1, cards: 3, cost: 4 },
    PackRow { key: "p_arcana_normal_4", kind: "Arcana", weight: 1.0, choose: 1, cards: 3, cost: 4 },
    PackRow { key: "p_arcana_jumbo_1", kind: "Arcana", weight: 1.0, choose: 1, cards: 5, cost: 6 },
    PackRow { key: "p_arcana_jumbo_2", kind: "Arcana", weight: 1.0, choose: 1, cards: 5, cost: 6 },
    PackRow { key: "p_arcana_mega_1", kind: "Arcana", weight: 0.25, choose: 2, cards: 5, cost: 8 },
    PackRow { key: "p_arcana_mega_2", kind: "Arcana", weight: 0.25, choose: 2, cards: 5, cost: 8 },
    PackRow { key: "p_celestial_normal_1", kind: "Celestial", weight: 1.0, choose: 1, cards: 3, cost: 4 },
    PackRow { key: "p_celestial_normal_2", kind: "Celestial", weight: 1.0, choose: 1, cards: 3, cost: 4 },
    PackRow { key: "p_celestial_normal_3", kind: "Celestial", weight: 1.0, choose: 1, cards: 3, cost: 4 },
    PackRow { key: "p_celestial_normal_4", kind: "Celestial", weight: 1.0, choose: 1, cards: 3, cost: 4 },
    PackRow { key: "p_celestial_jumbo_1", kind: "Celestial", weight: 1.0, choose: 1, cards: 5, cost: 6 },
    PackRow { key: "p_celestial_jumbo_2", kind: "Celestial", weight: 1.0, choose: 1, cards: 5, cost: 6 },
    PackRow { key: "p_celestial_mega_1", kind: "Celestial", weight: 0.25, choose: 2, cards: 5, cost: 8 },
    PackRow { key: "p_celestial_mega_2", kind: "Celestial", weight: 0.25, choose: 2, cards: 5, cost: 8 },
    PackRow { key: "p_standard_normal_1", kind: "Standard", weight: 1.0, choose: 1, cards: 3, cost: 4 },
    PackRow { key: "p_standard_normal_2", kind: "Standard", weight: 1.0, choose: 1, cards: 3, cost: 4 },
    PackRow { key: "p_standard_normal_3", kind: "Standard", weight: 1.0, choose: 1, cards: 3, cost: 4 },
    PackRow { key: "p_standard_normal_4", kind: "Standard", weight: 1.0, choose: 1, cards: 3, cost: 4 },
    PackRow { key: "p_standard_jumbo_1", kind: "Standard", weight: 1.0, choose: 1, cards: 5, cost: 6 },
    PackRow { key: "p_standard_jumbo_2", kind: "Standard", weight: 1.0, choose: 1, cards: 5, cost: 6 },
    PackRow { key: "p_standard_mega_1", kind: "Standard", weight: 0.25, choose: 2, cards: 5, cost: 8 },
    PackRow { key: "p_standard_mega_2", kind: "Standard", weight: 0.25, choose: 2, cards: 5, cost: 8 },
    PackRow { key: "p_buffoon_normal_1", kind: "Buffoon", weight: 0.6, choose: 1, cards: 2, cost: 4 },
    PackRow { key: "p_buffoon_normal_2", kind: "Buffoon", weight: 0.6, choose: 1, cards: 2, cost: 4 },
    PackRow { key: "p_buffoon_jumbo_1", kind: "Buffoon", weight: 0.6, choose: 1, cards: 4, cost: 6 },
    PackRow { key: "p_buffoon_mega_1", kind: "Buffoon", weight: 0.15, choose: 2, cards: 4, cost: 8 },
    PackRow { key: "p_spectral_normal_1", kind: "Spectral", weight: 0.3, choose: 1, cards: 2, cost: 4 },
    PackRow { key: "p_spectral_normal_2", kind: "Spectral", weight: 0.3, choose: 1, cards: 2, cost: 4 },
    PackRow { key: "p_spectral_jumbo_1", kind: "Spectral", weight: 0.3, choose: 1, cards: 4, cost: 6 },
    PackRow { key: "p_spectral_mega_1", kind: "Spectral", weight: 0.07, choose: 2, cards: 4, cost: 8 },
];
