//! Skip tags and their pool order, taken from the game.
//!
//! Generated by ops/gen_tag_data.py. Do not edit by hand.
//!
//! `min_ante` is the earliest ante a tag can be offered at, and `requires` names
//! a centre that has to have been discovered first. The order is the game's pool
//! order and is load-bearing: the draw picks an index into it.

/// One `(key, name, min_ante, requires)` row, in the game's pool order.
#[derive(Clone, Copy, Debug)]
pub struct TagRow {
    pub key: &'static str,
    pub name: &'static str,
    pub min_ante: i32,
    pub requires: &'static str,
}

/// (key, name, min_ante, requires), in the game's pool order.
pub const TAG_DATA: &[TagRow] = &[
    TagRow {
        key: "tag_uncommon",
        name: "Uncommon Tag",
        min_ante: 0,
        requires: "",
    },
    TagRow {
        key: "tag_rare",
        name: "Rare Tag",
        min_ante: 0,
        requires: "j_blueprint",
    },
    TagRow {
        key: "tag_negative",
        name: "Negative Tag",
        min_ante: 2,
        requires: "e_negative",
    },
    TagRow {
        key: "tag_foil",
        name: "Foil Tag",
        min_ante: 0,
        requires: "e_foil",
    },
    TagRow {
        key: "tag_holo",
        name: "Holographic Tag",
        min_ante: 0,
        requires: "e_holo",
    },
    TagRow {
        key: "tag_polychrome",
        name: "Polychrome Tag",
        min_ante: 0,
        requires: "e_polychrome",
    },
    TagRow {
        key: "tag_investment",
        name: "Investment Tag",
        min_ante: 0,
        requires: "",
    },
    TagRow {
        key: "tag_voucher",
        name: "Voucher Tag",
        min_ante: 0,
        requires: "",
    },
    TagRow {
        key: "tag_boss",
        name: "Boss Tag",
        min_ante: 0,
        requires: "",
    },
    TagRow {
        key: "tag_standard",
        name: "Standard Tag",
        min_ante: 2,
        requires: "",
    },
    TagRow {
        key: "tag_charm",
        name: "Charm Tag",
        min_ante: 0,
        requires: "",
    },
    TagRow {
        key: "tag_meteor",
        name: "Meteor Tag",
        min_ante: 2,
        requires: "",
    },
    TagRow {
        key: "tag_buffoon",
        name: "Buffoon Tag",
        min_ante: 2,
        requires: "",
    },
    TagRow {
        key: "tag_handy",
        name: "Handy Tag",
        min_ante: 2,
        requires: "",
    },
    TagRow {
        key: "tag_garbage",
        name: "Garbage Tag",
        min_ante: 2,
        requires: "",
    },
    TagRow {
        key: "tag_ethereal",
        name: "Ethereal Tag",
        min_ante: 2,
        requires: "",
    },
    TagRow {
        key: "tag_coupon",
        name: "Coupon Tag",
        min_ante: 0,
        requires: "",
    },
    TagRow {
        key: "tag_double",
        name: "Double Tag",
        min_ante: 0,
        requires: "",
    },
    TagRow {
        key: "tag_juggle",
        name: "Juggle Tag",
        min_ante: 0,
        requires: "",
    },
    TagRow {
        key: "tag_d_six",
        name: "D6 Tag",
        min_ante: 0,
        requires: "",
    },
    TagRow {
        key: "tag_top_up",
        name: "Top-up Tag",
        min_ante: 2,
        requires: "",
    },
    TagRow {
        key: "tag_skip",
        name: "Speed Tag",
        min_ante: 0,
        requires: "",
    },
    TagRow {
        key: "tag_orbital",
        name: "Orbital Tag",
        min_ante: 2,
        requires: "",
    },
    TagRow {
        key: "tag_economy",
        name: "Economy Tag",
        min_ante: 0,
        requires: "",
    },
];

/// The row with this display name.
pub fn tag_row(name: &str) -> Option<&'static TagRow> {
    TAG_DATA.iter().find(|row| row.name == name)
}

/// The row with this key.
pub fn tag_row_by_key(key: &str) -> Option<&'static TagRow> {
    TAG_DATA.iter().find(|row| row.key == key)
}
