//! Vouchers and their pool order, taken from the game.
//!
//! Generated by ops/gen_voucher_data.py. Do not edit by hand.
//!
//! `requires` names the voucher that has to have been redeemed first -- every
//! upgrade is gated on its base. `extra` is the number the effect is written in
//! terms of, and it is the only thing separating most upgrades from their base:
//! Grabber and Nacho Tong are the same effect with a different `extra`.
//!
//! The order is the game's pool order and is load-bearing: the draw picks an
//! index into it.

/// One `(key, name, cost, requires, extra)` row, in the game's pool order.
#[derive(Clone, Copy, Debug)]
pub struct VoucherRow {
    pub key: &'static str,
    pub name: &'static str,
    pub cost: i32,
    pub requires: &'static str,
    pub extra: f64,
}

/// (key, name, cost, requires, extra), in the game's pool order.
pub const VOUCHER_DATA: &[VoucherRow] = &[
    VoucherRow { key: "v_overstock_norm", name: "Overstock", cost: 10, requires: "", extra: 0.0 },
    VoucherRow { key: "v_overstock_plus", name: "Overstock Plus", cost: 10, requires: "v_overstock_norm", extra: 0.0 },
    VoucherRow { key: "v_clearance_sale", name: "Clearance Sale", cost: 10, requires: "", extra: 25.0 },
    VoucherRow { key: "v_liquidation", name: "Liquidation", cost: 10, requires: "v_clearance_sale", extra: 50.0 },
    VoucherRow { key: "v_hone", name: "Hone", cost: 10, requires: "", extra: 2.0 },
    VoucherRow { key: "v_glow_up", name: "Glow Up", cost: 10, requires: "v_hone", extra: 4.0 },
    VoucherRow { key: "v_reroll_surplus", name: "Reroll Surplus", cost: 10, requires: "", extra: 2.0 },
    VoucherRow { key: "v_reroll_glut", name: "Reroll Glut", cost: 10, requires: "v_reroll_surplus", extra: 2.0 },
    VoucherRow { key: "v_crystal_ball", name: "Crystal Ball", cost: 10, requires: "", extra: 3.0 },
    VoucherRow { key: "v_omen_globe", name: "Omen Globe", cost: 10, requires: "v_crystal_ball", extra: 4.0 },
    VoucherRow { key: "v_telescope", name: "Telescope", cost: 10, requires: "", extra: 3.0 },
    VoucherRow { key: "v_observatory", name: "Observatory", cost: 10, requires: "v_telescope", extra: 1.5 },
    VoucherRow { key: "v_grabber", name: "Grabber", cost: 10, requires: "", extra: 1.0 },
    VoucherRow { key: "v_nacho_tong", name: "Nacho Tong", cost: 10, requires: "v_grabber", extra: 1.0 },
    VoucherRow { key: "v_wasteful", name: "Wasteful", cost: 10, requires: "", extra: 1.0 },
    VoucherRow { key: "v_recyclomancy", name: "Recyclomancy", cost: 10, requires: "v_wasteful", extra: 1.0 },
    VoucherRow { key: "v_tarot_merchant", name: "Tarot Merchant", cost: 10, requires: "", extra: 2.4 },
    VoucherRow { key: "v_tarot_tycoon", name: "Tarot Tycoon", cost: 10, requires: "v_tarot_merchant", extra: 8.0 },
    VoucherRow { key: "v_planet_merchant", name: "Planet Merchant", cost: 10, requires: "", extra: 2.4 },
    VoucherRow { key: "v_planet_tycoon", name: "Planet Tycoon", cost: 10, requires: "v_planet_merchant", extra: 8.0 },
    VoucherRow { key: "v_seed_money", name: "Seed Money", cost: 10, requires: "", extra: 50.0 },
    VoucherRow { key: "v_money_tree", name: "Money Tree", cost: 10, requires: "v_seed_money", extra: 100.0 },
    VoucherRow { key: "v_blank", name: "Blank", cost: 10, requires: "", extra: 5.0 },
    VoucherRow { key: "v_antimatter", name: "Antimatter", cost: 10, requires: "v_blank", extra: 15.0 },
    VoucherRow { key: "v_magic_trick", name: "Magic Trick", cost: 10, requires: "", extra: 4.0 },
    VoucherRow { key: "v_illusion", name: "Illusion", cost: 10, requires: "v_magic_trick", extra: 4.0 },
    VoucherRow { key: "v_hieroglyph", name: "Hieroglyph", cost: 10, requires: "", extra: 1.0 },
    VoucherRow { key: "v_petroglyph", name: "Petroglyph", cost: 10, requires: "v_hieroglyph", extra: 1.0 },
    VoucherRow { key: "v_directors_cut", name: "Director's Cut", cost: 10, requires: "", extra: 10.0 },
    VoucherRow { key: "v_retcon", name: "Retcon", cost: 10, requires: "v_directors_cut", extra: 10.0 },
    VoucherRow { key: "v_paint_brush", name: "Paint Brush", cost: 10, requires: "", extra: 1.0 },
    VoucherRow { key: "v_palette", name: "Palette", cost: 10, requires: "v_paint_brush", extra: 1.0 },
];

/// The row with this display name.
pub fn voucher_row(name: &str) -> Option<&'static VoucherRow> {
    VOUCHER_DATA.iter().find(|row| row.name == name)
}
